/* =========================================================
   بيانات تجريبية محلية (Demo Mode)
   تُستخدم تلقائيًا إن لم يتم ضبط بيانات Supabase في config.js
   نسخة مُعاد كتابتها بالكامل: أسئلة جديدة تمامًا، تم التحقق من
   دقتها الواقعية وصياغتها بحيث لا تكشف الإجابة داخل نص السؤال.
   ========================================================= */

const QUIZ_CATEGORIES = [
  { id: "science",    name: "العلوم",          icon: "🔬" },
  { id: "technology", name: "التقنية",         icon: "💻" },
  { id: "history",    name: "التاريخ",         icon: "📜" },
  { id: "geography",  name: "الجغرافيا",       icon: "🌍" },
  { id: "culture",    name: "ثقافة عامة",      icon: "🧠" },
  { id: "body",       name: "جسم الإنسان",     icon: "🧬" },
  { id: "sports",     name: "الرياضة",         icon: "⚽" },
  { id: "ai",         name: "الذكاء الاصطناعي", icon: "🤖" },
  { id: "religion",   name: "الدين",           icon: "🕌" },
];

function catName(id){
  const c = QUIZ_CATEGORIES.find(c => c.id === id);
  return c ? c.name : id;
}
function catIcon(id){
  const c = QUIZ_CATEGORIES.find(c => c.id === id);
  return c ? c.icon : "❓";
}

/* كل سؤال: question, option1..4, correct_answer(1-4), category,
   age_min, age_max, difficulty(easy|medium|hard), points, explanation */
const DEMO_QUESTIONS = [

  // ==========================================
  // ---- العلوم (SCIENCE - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"كم عدد الكواكب في مجموعتنا الشمسية؟", option1:"6", option2:"7", option3:"8", option4:"9", correct_answer:3, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يضم النظام الشمسي 8 كواكب بعد استبعاد بلوتو من قائمة الكواكب الرئيسية عام 2006." },
  { question:"ما هو الغاز الذي يحتاجه الإنسان للتنفس والبقاء على قيد الحياة؟", option1:"النيتروجين", option2:"الأكسجين", option3:"الهيدروجين", option4:"الهيليوم", correct_answer:2, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يستخدم جسم الإنسان الأكسجين لإنتاج الطاقة داخل الخلايا." },
  { question:"ما هي الوحدة الشائعة لقياس درجة الحرارة في معظم دول العالم؟", option1:"المتر", option2:"اللتر", option3:"الدرجة المئوية", option4:"الكيلوغرام", correct_answer:3, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الدرجة المئوية (سيلسيوس) هي وحدة قياس الحرارة الأكثر انتشارًا عالميًا." },
  { question:"أي من التالي كائن حي مكوّن من خلية واحدة فقط؟", option1:"النحلة", option2:"البكتيريا", option3:"الفراشة", option4:"السمكة", correct_answer:2, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"البكتيريا كائنات وحيدة الخلية بينما بقية الخيارات كائنات متعددة الخلايا." },
  { question:"ما هو المصدر الطبيعي الأساسي للضوء والحرارة على كوكب الأرض؟", option1:"القمر", option2:"الرياح", option3:"الشمس", option4:"البراكين", correct_answer:3, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الشمس هي المصدر الرئيسي للطاقة الضوئية والحرارية على الأرض." },
  { question:"ما اسم العملية التي تصنع بها النباتات غذاءها من ضوء الشمس؟", option1:"التنفس", option2:"البناء الضوئي", option3:"الهضم", option4:"التبخر", correct_answer:2, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"البناء الضوئي عملية تحوّل بها النباتات ضوء الشمس والماء وثاني أكسيد الكربون إلى غذاء وأكسجين." },
  { question:"أي حالة من حالات المادة ليس لها شكل ثابت ولا حجم ثابت؟", option1:"الصلبة", option2:"السائلة", option3:"الغازية", option4:"البلورية", correct_answer:3, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الغازات تنتشر لتملأ أي وعاء توضع فيه، فلا شكل ولا حجم ثابت لها." },
  { question:"ما اسم القوة التي تجعل الأجسام تسقط نحو الأرض؟", option1:"المغناطيسية", option2:"الجاذبية", option3:"الاحتكاك", option4:"الطفو", correct_answer:2, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الجاذبية الأرضية تجذب الأجسام نحو مركز الأرض." },
  { question:"ما هي أصغر وحدة بنائية تتكون منها أجسام الكائنات الحية؟", option1:"النسيج", option2:"العضو", option3:"الخلية", option4:"الجهاز", correct_answer:3, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الخلية هي الوحدة الأساسية للبناء والوظيفة في كل الكائنات الحية." },
  { question:"ما اسم الأداة التي تُستخدم لقياس وزن الأشياء؟", option1:"المسطرة", option2:"الميزان", option3:"الساعة", option4:"البوصلة", correct_answer:2, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الميزان أداة أساسية لقياس كتلة أو وزن الأجسام." },

  // متوسطة (10)
  { question:"ما هو الرمز الكيميائي لعنصر الذهب؟", option1:"Go", option2:"Gd", option3:"Au", option4:"Ag", correct_answer:3, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يرمز للذهب بالحرفين Au، مشتقة من اسمه اللاتيني Aurum." },
  { question:"أي كواكب المجموعة الشمسية يدور حول نفسه بأسرع معدل؟", option1:"الأرض", option2:"المشتري", option3:"زحل", option4:"عطارد", correct_answer:2, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يكمل كوكب المشتري دورة كاملة حول نفسه في أقل من 10 ساعات، وهو الأسرع بين الكواكب." },
  { question:"من هو العالم الذي وضع القوانين الثلاثة الأساسية للحركة؟", option1:"ألبرت أينشتاين", option2:"إسحاق نيوتن", option3:"غاليليو غاليلي", option4:"تشارلز داروين", correct_answer:2, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"صاغ إسحاق نيوتن قوانين الحركة الثلاثة في كتابه الشهير عام 1687." },
  { question:"ما هو الغاز الذي تُطلقه النباتات كناتج ثانوي أثناء عملية البناء الضوئي؟", option1:"ثاني أكسيد الكربون", option2:"النيتروجين", option3:"الأكسجين", option4:"الهيدروجين", correct_answer:3, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تمتص النباتات ثاني أكسيد الكربون وتُطلق الأكسجين أثناء البناء الضوئي." },
  { question:"ما اسم المجرة التي ينتمي إليها كوكب الأرض والنظام الشمسي؟", option1:"مجرة المرأة المسلسلة", option2:"درب التبانة", option3:"مجرة العنقاء", option4:"مجرة أندروميدا", correct_answer:2, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يقع نظامنا الشمسي داخل مجرة درب التبانة (Milky Way)." },
  { question:"أي العناصر الكيميائية التالية هو الأخف وزنًا في الجدول الدوري؟", option1:"الهيليوم", option2:"الهيدروجين", option3:"الأكسجين", option4:"النيتروجين", correct_answer:2, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الهيدروجين هو أخف وأبسط العناصر الكيميائية، وأول عنصر في الجدول الدوري." },
  { question:"ما اسم الطبقة الصلبة الخارجية التي نعيش عليها من كوكب الأرض؟", option1:"النواة", option2:"الوشاح", option3:"القشرة الأرضية", option4:"الغلاف الجوي", correct_answer:3, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"القشرة الأرضية هي الطبقة الصخرية الصلبة الخارجية التي نقف عليها." },
  { question:"كم تبلغ سرعة الصوت تقريبًا في الهواء عند مستوى سطح البحر؟", option1:"340 مترًا في الثانية", option2:"3000 متر في الثانية", option3:"34 مترًا في الثانية", option4:"340000 متر في الثانية", correct_answer:1, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تبلغ سرعة الصوت في الهواء حوالي 340 م/ث، وهي أبطأ بكثير من سرعة الضوء." },
  { question:"ما اسم العملية التي يتحول فيها بخار الماء مباشرة إلى قطرات سائلة؟", option1:"التبخر", option2:"التكاثف", option3:"الانصهار", option4:"التسامي", correct_answer:2, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"التكاثف هو تحول الغاز إلى سائل، كما يحدث عند تكوّن قطرات الندى." },
  { question:"أي غدة في جسم الإنسان تُفرز الهرمونات المسؤولة عن تنظيم عملية الأيض؟", option1:"الغدة الدرقية", option2:"الكبد", option3:"الطحال", option4:"البنكرياس", correct_answer:1, category:"science", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تفرز الغدة الدرقية هرمون الثيروكسين الذي ينظم معدل الأيض في الجسم." },

  // صعبة (10)
  { question:"من هو العالم الذي وضع أسس علم الوراثة الحديث من خلال تجاربه على نبات البازلاء؟", option1:"تشارلز داروين", option2:"غريغور مندل", option3:"جان لامارك", option4:"لويس باستور", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُعتبر الراهب النمساوي غريغور مندل أبا علم الوراثة الحديث." },
  { question:"ما اسم الجسيم دون الذري الذي لا يحمل أي شحنة كهربائية داخل نواة الذرة؟", option1:"البروتون", option2:"الإلكترون", option3:"النيوترون", option4:"الفوتون", correct_answer:3, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"النيوترون جسيم متعادل الشحنة يوجد بجانب البروتونات داخل نواة الذرة." },
  { question:"ما هي وحدة قياس الطاقة في النظام الدولي؟", option1:"النيوتن", option2:"الجول", option3:"الواط", option4:"الباسكال", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"الجول هو الوحدة الأساسية لقياس الطاقة والشغل في النظام الدولي." },
  { question:"من هو العالم الذي يُنسب إليه اكتشاف مادة البنسلين المضادة للبكتيريا؟", option1:"لويس باستور", option2:"ألكسندر فليمنج", option3:"ماري كوري", option4:"ديمتري مندليف", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"اكتشف ألكسندر فليمنج البنسلين مصادفة عام 1928، أول مضاد حيوي حقيقي." },
  { question:"ما اسم النظرية العلمية التي تفسّر نشأة الكون بحدوث انفجار هائل قبل مليارات السنين؟", option1:"نظرية التطور", option2:"نظرية الانفجار العظيم", option3:"النظرية النسبية", option4:"ميكانيكا الكم", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تصف نظرية الانفجار العظيم (Big Bang) بداية توسع الكون من نقطة شديدة الكثافة." },
  { question:"ما اسم العملية التي تحوّل بها خلايا الجسم الطاقة الكيميائية المخزنة في الغذاء إلى طاقة قابلة للاستخدام؟", option1:"التنفس الخلوي", option2:"البناء الضوئي", option3:"الانقسام الخلوي", option4:"النتح", correct_answer:1, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"التنفس الخلوي يحرر الطاقة المخزنة في الغذاء على شكل جزيئات ATP القابلة للاستخدام." },
  { question:"من هو العالم الروسي الذي وضع الصيغة الحديثة للجدول الدوري للعناصر؟", option1:"ديمتري مندليف", option2:"نيلز بور", option3:"إرنست رذرفورد", option4:"ماري كوري", correct_answer:1, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"رتّب مندليف عام 1869 العناصر الكيميائية في جدول دوري بحسب خصائصها المتكررة." },
  { question:"ما اسم الأشعة غير المرئية ذات الطول الموجي الأقصر من الضوء المرئي والمسؤولة عن حروق الشمس؟", option1:"الأشعة تحت الحمراء", option2:"الأشعة فوق البنفسجية", option3:"موجات الميكروويف", option4:"أشعة غاما", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"الأشعة فوق البنفسجية القادمة من الشمس هي المسؤولة عن حروق الجلد الشمسية." },
  { question:"أي من العناصر التالية يُعتبر غازًا خاملاً نادرًا ما يتفاعل كيميائيًا؟", option1:"الصوديوم", option2:"الكلور", option3:"الأرجون", option4:"الحديد", correct_answer:3, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"الأرجون من الغازات النبيلة (الخاملة) التي نادرًا ما تدخل في تفاعلات كيميائية." },
  { question:"ما اسم الجسيم الذي يحمل القوة الكهرومغناطيسية بين الجسيمات المشحونة وفق النموذج القياسي للفيزياء؟", option1:"الغلوون", option2:"الفوتون", option3:"بوزون W", option4:"الجرافيتون", correct_answer:2, category:"science", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"الفوتون هو حامل القوة الكهرومغناطيسية، وهو أيضًا الجسيم الأساسي المكوّن للضوء." },

  // ==========================================
  // ---- التقنية (TECHNOLOGY - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"ما اسم الجهاز المستخدم لطباعة المستندات على الورق؟", option1:"الماسح الضوئي", option2:"الطابعة", option3:"الفأرة", option4:"الشاشة", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الطابعة تحوّل الملفات الرقمية إلى نسخ ورقية مطبوعة." },
  { question:"أي مما يلي يُعد نظام تشغيل لأجهزة الحاسوب؟", option1:"Windows", option2:"Photoshop", option3:"Excel", option4:"Chrome", correct_answer:1, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"Windows نظام تشغيل، بينما بقية الخيارات برامج تعمل فوق نظام التشغيل." },
  { question:"ما اسم الرمز الذي يظهر في كل عنوان بريد إلكتروني ويفصل بين اسم المستخدم والنطاق؟", option1:"#", option2:"@", option3:"%", option4:"&", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُستخدم الرمز @ للفصل بين اسم المستخدم واسم مزوّد الخدمة في عناوين البريد الإلكتروني." },
  { question:"أي وحدة تخزين بيانات أكبر من الميغابايت؟", option1:"البايت", option2:"الجيجابايت", option3:"البت", option4:"الهيرتز", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الجيجابايت أكبر من الميغابايت بحوالي 1024 مرة." },
  { question:"أي جهاز يُستخدم لتحريك المؤشر والنقر على الشاشة؟", option1:"لوحة المفاتيح", option2:"الفأرة", option3:"السماعة", option4:"الميكروفون", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الفأرة (Mouse) هي أداة الإدخال الأساسية لتحريك المؤشر والنقر." },
  { question:"ما اسم الشبكة العالمية التي تربط ملايين الأجهزة حول العالم؟", option1:"الإنترانت", option2:"الإنترنت", option3:"البلوتوث", option4:"الشبكة المحلية", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الإنترنت شبكة عالمية تربط الأجهزة والحواسيب في كل أنحاء العالم." },
  { question:"أي مما يلي يُعتبر متصفح إنترنت؟", option1:"Word", option2:"Chrome", option3:"Excel", option4:"PowerPoint", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"Chrome متصفح ويب يُستخدم لتصفح مواقع الإنترنت." },
  { question:"ما اسم الجزء في الحاسوب الذي يخزّن البيانات بشكل دائم حتى بعد إيقاف التشغيل؟", option1:"الذاكرة العشوائية RAM", option2:"القرص الصلب", option3:"المعالج", option4:"الشاشة", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"القرص الصلب يحتفظ بالبيانات بشكل دائم، بخلاف الذاكرة العشوائية التي تُمسح عند إيقاف التشغيل." },
  { question:"ما امتداد الملف الشائع للصور الرقمية؟", option1:".mp3", option2:".jpg", option3:".exe", option4:".txt", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُستخدم امتداد jpg. بشكل واسع لتخزين الصور الرقمية المضغوطة." },
  { question:"ما اسم البرنامج المستخدم لكتابة وتحرير النصوص الأساسية في نظام Windows؟", option1:"Paint", option2:"Notepad", option3:"Calculator", option4:"CMD", correct_answer:2, category:"technology", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"برنامج Notepad محرر نصوص بسيط مدمج في نظام Windows." },

  // متوسطة (10)
  { question:"ماذا يعني اختصار URL الذي نكتبه في شريط عنوان المتصفح؟", option1:"عنوان صفحة الويب", option2:"نوع الملف", option3:"برنامج حماية", option4:"نظام تشغيل", correct_answer:1, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"URL هو العنوان الفريد الذي يحدد موقع صفحة أو ملف على الإنترنت." },
  { question:"أي لغة برمجة تُستخدم رسميًا لتطوير تطبيقات أندرويد الحديثة؟", option1:"Swift", option2:"Kotlin", option3:"C#", option4:"Ruby", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"اعتمدت جوجل لغة Kotlin كلغة رسمية مفضلة لتطوير تطبيقات أندرويد." },
  { question:"ما اسم البروتوكول الأساسي المستخدم لنقل صفحات الويب بين المتصفح والخادم؟", option1:"FTP", option2:"HTTP", option3:"SMTP", option4:"POP3", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"بروتوكول HTTP هو الأساس الذي تُنقل عبره صفحات الويب." },
  { question:"ما هي الوظيفة الأساسية لبرنامج \"الجدار الناري\" (Firewall)؟", option1:"تسريع الاتصال بالإنترنت", option2:"حماية الشبكة من الوصول غير المصرح به", option3:"تخزين الملفات احتياطيًا", option4:"تشغيل ملفات الفيديو", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الجدار الناري يراقب حركة البيانات ويمنع الوصول غير المصرّح به للشبكة." },
  { question:"أي شركة هي المطوّر الأساسي لنظام تشغيل أندرويد؟", option1:"Apple", option2:"Microsoft", option3:"Google", option4:"Samsung", correct_answer:3, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"طوّرت شركة جوجل نظام أندرويد وتديره حتى اليوم." },
  { question:"أي أنواع ذاكرة الحاسوب تفقد محتواها فور إيقاف تشغيل الجهاز؟", option1:"الذاكرة العشوائية RAM", option2:"ذاكرة القراءة فقط ROM", option3:"القرص الصلب", option4:"ذاكرة الفلاش", correct_answer:1, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الذاكرة العشوائية RAM ذاكرة مؤقتة تُمسح بمجرد فصل الطاقة عن الجهاز." },
  { question:"ما هو الغرض الأساسي من تثبيت برنامج مكافحة الفيروسات؟", option1:"تسريع الجهاز", option2:"حماية النظام من البرمجيات الخبيثة", option3:"تنظيف الشاشة", option4:"تحرير الصور", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يكتشف برنامج مكافحة الفيروسات البرمجيات الضارة ويزيلها لحماية الجهاز." },
  { question:"أي مما يلي يُستخدم لتخزين الملفات ومزامنتها عبر الإنترنت بدلاً من القرص الصلب؟", option1:"التخزين السحابي", option2:"القرص المرن", option3:"الشريط المغناطيسي", option4:"البطاقة المثقبة", correct_answer:1, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"التخزين السحابي يحفظ الملفات على خوادم بعيدة يمكن الوصول إليها من أي جهاز متصل بالإنترنت." },
  { question:"ما اسم اللغة المستخدمة أساسًا لتنسيق مظهر صفحات الويب (الألوان والتخطيط)؟", option1:"HTML", option2:"CSS", option3:"Python", option4:"Java", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"CSS هي لغة التنسيق المسؤولة عن مظهر وتخطيط صفحات الويب." },
  { question:"ماذا يصف مصطلح \"الجيل الخامس\" أو 5G في عالم الاتصالات؟", option1:"نوع كابل شبكة", option2:"جيل حديث من تقنية الاتصال اللاسلكي عالي السرعة", option3:"نوع طابعة", option4:"برنامج مكافحة فيروسات", correct_answer:2, category:"technology", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"5G هو الجيل الخامس من شبكات الجوال، ويوفر سرعات نقل بيانات أعلى بكثير من الأجيال السابقة." },

  // صعبة (10)
  { question:"ما اسم أول دودة حاسوبية (Worm) انتشرت عبر الإنترنت على نطاق واسع عام 1988؟", option1:"ILOVEYOU", option2:"Morris Worm", option3:"Stuxnet", option4:"Melissa", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"صمّمها روبرت موريس عام 1988، وتُعد من أوائل الهجمات الكبرى عبر الإنترنت." },
  { question:"أي شركة أطلقت أول جهاز آيفون تجاريًا عام 2007؟", option1:"سامسونج", option2:"نوكيا", option3:"آبل", option4:"بلاك بيري", correct_answer:3, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أطلقت شركة آبل أول آيفون عام 2007 وغيّرت به صناعة الهواتف الذكية." },
  { question:"ما اسم المعمارية التي تعتمد عليها غالبية معالجات الحواسيب المكتبية والمحمولة التقليدية؟", option1:"ARM", option2:"x86", option3:"RISC-V", option4:"MIPS", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"هيمنت معمارية x86 تاريخيًا على معالجات أجهزة الحاسوب المكتبية والمحمولة." },
  { question:"ما هو الفرق الجوهري بين بروتوكولي HTTP و HTTPS؟", option1:"السرعة فقط", option2:"وجود تشفير للبيانات المنقولة في HTTPS", option3:"حجم الملفات المنقولة", option4:"نوع المتصفح المستخدم", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يضيف الحرف S في HTTPS طبقة تشفير (SSL/TLS) لحماية البيانات المتبادلة." },
  { question:"ما اسم تقنية تخزين البيانات الموزّعة وغير القابلة للتعديل التي تعتمد عليها العملات الرقمية؟", option1:"قاعدة بيانات علائقية", option2:"سلسلة الكتل (Blockchain)", option3:"التخزين السحابي", option4:"الذاكرة الومضية", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"سلسلة الكتل دفتر بيانات موزّع لا يمكن تعديل سجلاته بعد تثبيتها." },
  { question:"من هو الشريك المؤسس الذي أسس شركة مايكروسوفت جنبًا إلى جنب مع بيل غيتس؟", option1:"ستيف جوبز", option2:"بول ألين", option3:"لاري بيج", option4:"مارك زوكربيرغ", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أسس بول ألين شركة مايكروسوفت مع بيل غيتس عام 1975." },
  { question:"ما اسم بروتوكول أمان شبكات الواي فاي الذي حلّ محل بروتوكول WEP القديم غير الآمن؟", option1:"WPA", option2:"FTP", option3:"SSH", option4:"SMTP", correct_answer:1, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استُحدث بروتوكول WPA لتقوية حماية شبكات الواي فاي بعد ثغرات WEP." },
  { question:"أي نوع من قواعد البيانات ينظّم المعلومات في جداول مرتبطة بعلاقات فيما بينها؟", option1:"قاعدة بيانات NoSQL", option2:"قاعدة بيانات علائقية", option3:"قاعدة بيانات رسم بياني", option4:"تخزين مفتاح-قيمة", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تعتمد قواعد البيانات العلائقية على تنظيم البيانات في جداول مترابطة عبر مفاتيح." },
  { question:"ما اسم اللغة المصمَّمة خصيصًا للاستعلام عن قواعد البيانات العلائقية والتعامل معها؟", option1:"HTML", option2:"SQL", option3:"XML", option4:"JSON", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"SQL هي لغة الاستعلام القياسية للتعامل مع قواعد البيانات العلائقية." },
  { question:"ما هو الاسم الشائع لممارسة اختبار أمان الأنظمة عبر محاولة اختراقها بإذن مسبق من مالكها؟", option1:"القرصنة الخبيثة", option2:"اختبار الاختراق الأخلاقي", option3:"الهندسة الاجتماعية", option4:"التصيّد الاحتيالي", correct_answer:2, category:"technology", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"اختبار الاختراق الأخلاقي يُجرى بإذن رسمي لاكتشاف الثغرات الأمنية وإصلاحها." },

  // ==========================================
  // ---- التاريخ (HISTORY - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"في أي قارة قامت الحضارة المصرية القديمة؟", option1:"آسيا", option2:"أفريقيا", option3:"أوروبا", option4:"أستراليا", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"ازدهرت الحضارة المصرية القديمة على ضفاف نهر النيل في قارة أفريقيا." },
  { question:"من هو أول رئيس للولايات المتحدة الأمريكية؟", option1:"أبراهام لينكولن", option2:"جورج واشنطن", option3:"توماس جيفرسون", option4:"بنجامين فرانكلين", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تولى جورج واشنطن أول رئاسة للولايات المتحدة عام 1789." },
  { question:"ما اسم السفينة الشهيرة التي اصطدمت بجبل جليدي وغرقت عام 1912؟", option1:"تايتانيك", option2:"بسمارك", option3:"مايفلاور", option4:"فيكتوريا", correct_answer:1, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"غرقت سفينة تايتانيك في رحلتها الأولى عبر المحيط الأطلسي عام 1912." },
  { question:"في أي دولة تقع أهرامات الجيزة الشهيرة؟", option1:"السعودية", option2:"مصر", option3:"العراق", option4:"الأردن", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تقع أهرامات الجيزة الثلاثة الكبرى في مصر، وبُنيت في عصر الدولة القديمة." },
  { question:"من هو القائد الذي دخل مكة المكرمة فاتحًا على رأس المسلمين عام الفتح؟", option1:"عمر بن الخطاب", option2:"النبي محمد ﷺ", option3:"خالد بن الوليد", option4:"أبو بكر الصديق", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"قاد النبي محمد ﷺ المسلمين في فتح مكة سنة 8 للهجرة." },
  { question:"أي حضارة قديمة بنت سور الصين العظيم؟", option1:"اليابانية", option2:"الصينية", option3:"الكورية", option4:"المنغولية", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"شيّدت السلالات الصينية المتعاقبة سور الصين العظيم عبر قرون طويلة." },
  { question:"في أي عام انتهت الحرب العالمية الثانية؟", option1:"1918", option2:"1945", option3:"1939", option4:"1950", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"انتهت الحرب العالمية الثانية عام 1945 باستسلام ألمانيا واليابان." },
  { question:"من هو المستكشف الذي وصلت رحلته إلى قارة أمريكا عام 1492 حسب السجلات الأوروبية؟", option1:"فرديناند ماجلان", option2:"كريستوفر كولومبوس", option3:"فاسكو دي غاما", option4:"جون كابوت", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"وصلت بعثة كولومبوس إلى الأمريكتين عام 1492، وهو ما وثّقته السجلات الأوروبية آنذاك." },
  { question:"من حكم مصر القديمة ويُطلق عليهم لقب ملوك ذلك العصر؟", option1:"الأباطرة", option2:"الفراعنة", option3:"القياصرة", option4:"السلاطين", correct_answer:2, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"عُرف حكّام مصر القديمة بلقب الفراعنة." },
  { question:"في أي موقع وقعت غزوة بدر الكبرى بين المسلمين وقريش؟", option1:"المدينة المنورة", option2:"مكة المكرمة", option3:"بدر", option4:"الطائف", correct_answer:3, category:"history", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"وقعت غزوة بدر الكبرى في منطقة بدر الواقعة بين مكة والمدينة." },

  // متوسطة (10)
  { question:"من هو القائد المسلم الذي انتصر على الفرس في معركة القادسية؟", option1:"خالد بن الوليد", option2:"سعد بن أبي وقاص", option3:"عمرو بن العاص", option4:"طارق بن زياد", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"قاد سعد بن أبي وقاص جيش المسلمين في معركة القادسية ضد الفرس." },
  { question:"في أي قرن تقريبًا بدأت الثورة الصناعية في أوروبا؟", option1:"القرن السادس عشر", option2:"القرن الثامن عشر", option3:"القرن العشرون", option4:"القرن الرابع عشر", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"انطلقت الثورة الصناعية في بريطانيا خلال القرن الثامن عشر." },
  { question:"من هو الملك الذي وحّد مناطق شبه الجزيرة العربية وأسس المملكة العربية السعودية الحديثة؟", option1:"الملك فيصل بن عبدالعزيز", option2:"الملك عبدالعزيز آل سعود", option3:"الملك سعود بن عبدالعزيز", option4:"الملك خالد بن عبدالعزيز", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"أسس الملك عبدالعزيز آل سعود المملكة العربية السعودية الحديثة عام 1932." },
  { question:"من هي الملكة التي حكمت مصر القديمة وارتبط اسمها بعلاقتها بيوليوس قيصر ومارك أنطونيو؟", option1:"نفرتيتي", option2:"كليوباترا", option3:"حتشبسوت", option4:"زنوبيا", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"كانت كليوباترا السابعة آخر ملكة فعلية لمصر القديمة قبل ضمّها لروما." },
  { question:"في أي عام سقطت الإمبراطورية الرومانية الغربية؟", option1:"476 ميلادي", option2:"1453 ميلادي", option3:"1000 ميلادي", option4:"300 ميلادي", correct_answer:1, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يؤرَّخ لسقوط الإمبراطورية الرومانية الغربية بعام 476م." },
  { question:"ما اسم المعاهدة التي أنهت رسميًا الحرب العالمية الأولى؟", option1:"معاهدة فرساي", option2:"معاهدة يالطا", option3:"معاهدة باريس", option4:"معاهدة لندن", correct_answer:1, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"وُقّعت معاهدة فرساي عام 1919 لإنهاء الحرب العالمية الأولى رسميًا." },
  { question:"من هو القائد القرطاجي الذي عبر جبال الألب بجيشه وفيلته لمهاجمة روما؟", option1:"يوليوس قيصر", option2:"هانيبال", option3:"الإسكندر الأكبر", option4:"سبارتاكوس", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"قاد هانيبال حملته الشهيرة عبر جبال الألب خلال الحرب البونية الثانية." },
  { question:"ما اسم الثورة التي أطاحت بالنظام الملكي المطلق في فرنسا عام 1789؟", option1:"الثورة الصناعية", option2:"الثورة الفرنسية", option3:"ثورة أكتوبر", option4:"الثورة الأمريكية", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"غيّرت الثورة الفرنسية عام 1789 النظام السياسي في فرنسا جذريًا." },
  { question:"من هو الخليفة الذي وحّد نصوص القرآن الكريم في مصحف واحد رسمي وأرسل نسخًا منه إلى الأمصار؟", option1:"أبو بكر الصديق", option2:"عمر بن الخطاب", option3:"عثمان بن عفان", option4:"علي بن أبي طالب", correct_answer:3, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"في عهد عثمان بن عفان تم توحيد المصحف في نسخة رسمية واحدة توزّعت على الأمصار الإسلامية." },
  { question:"ما اسم الجدار الذي قسّم مدينة برلين خلال فترة الحرب الباردة؟", option1:"جدار الصين", option2:"جدار برلين", option3:"الستار الحديدي", option4:"جدار المكسيك", correct_answer:2, category:"history", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"فصل جدار برلين شطري المدينة من عام 1961 حتى سقوطه عام 1989." },

  // صعبة (10)
  { question:"في أي عام وقعت معركة عين جالوت التي أوقفت زحف المغول نحو مصر والشام؟", option1:"1260 ميلادي", option2:"1187 ميلادي", option3:"1099 ميلادي", option4:"1453 ميلادي", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"هزم المماليك المغول في معركة عين جالوت عام 1260م بقيادة قطز وبيبرس." },
  { question:"من هو الإمبراطور الفرنسي الذي هُزم نهائيًا في معركة واترلو عام 1815؟", option1:"لويس السادس عشر", option2:"نابليون بونابرت", option3:"شارلمان", option4:"لويس فيليب", correct_answer:2, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"انتهت مسيرة نابليون العسكرية بهزيمته في معركة واترلو عام 1815." },
  { question:"ما اسم الاتفاقية السرية التي قسّمت مناطق النفوذ بين بريطانيا وفرنسا في الشرق الأوسط بعد الحرب العالمية الأولى؟", option1:"اتفاقية سايكس-بيكو", option2:"معاهدة فرساي", option3:"وعد بلفور", option4:"اتفاقية كامب ديفيد", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"وُقّعت اتفاقية سايكس-بيكو عام 1916 لتقسيم مناطق النفوذ بين الدولتين." },
  { question:"من هو مؤسس الدولة العباسية الذي لُقّب بـ\"السفّاح\"؟", option1:"أبو العباس السفاح", option2:"هارون الرشيد", option3:"المأمون", option4:"أبو جعفر المنصور", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أسس أبو العباس السفاح الخلافة العباسية عام 132هـ بعد سقوط الأمويين." },
  { question:"في أي معركة انتصر المسلمون على جيش الروم البيزنطي وفتحوا بلاد الشام عام 636م؟", option1:"معركة اليرموك", option2:"معركة حطين", option3:"معركة بدر", option4:"معركة أحد", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"حسمت معركة اليرموك سيطرة المسلمين على بلاد الشام عام 636م." },
  { question:"ما اسم الأزمة الدولية التي كادت تشعل حربًا نووية بين الولايات المتحدة والاتحاد السوفيتي عام 1962؟", option1:"أزمة برلين", option2:"أزمة الصواريخ الكوبية", option3:"أزمة قناة السويس", option4:"أزمة كوريا", correct_answer:2, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"وضعت أزمة الصواريخ الكوبية عام 1962 العالم على حافة مواجهة نووية مباشرة." },
  { question:"من هو القائد المغولي الذي أسس أكبر إمبراطورية متصلة الأرجاء في التاريخ خلال القرن الثالث عشر؟", option1:"تيمورلنك", option2:"جنكيز خان", option3:"قوبلاي خان", option4:"هولاكو خان", correct_answer:2, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أسس جنكيز خان الإمبراطورية المغولية ووسّعها لتصبح الأكبر في التاريخ." },
  { question:"ما اسم الوثيقة التي وقّعها الملك جون الإنجليزي عام 1215 وقيّدت سلطاته المطلقة؟", option1:"الماغنا كارتا", option2:"إعلان الاستقلال", option3:"العريضة الكبرى للحقوق", option4:"دستور وستمنستر", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُعد الماغنا كارتا من أوائل الوثائق التي حدّت من سلطة الملوك في التاريخ الأوروبي." },
  { question:"أي سنة هجرية تُعد بداية التقويم الهجري بحسب هجرة النبي ﷺ من مكة إلى المدينة؟", option1:"السنة الأولى للهجرة", option2:"السنة الخامسة للهجرة", option3:"السنة العاشرة للهجرة", option4:"السنة الثانية للهجرة", correct_answer:1, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"اعتُمدت سنة الهجرة النبوية كنقطة بداية للتقويم الهجري في عهد عمر بن الخطاب." },
  { question:"أي سلاطين الدولة العثمانية لُقّب بـ\"القانوني\" لتطويره الأنظمة القانونية والإدارية للدولة؟", option1:"محمد الفاتح", option2:"سليمان القانوني", option3:"سليم الأول", option4:"بايزيد الأول", correct_answer:2, category:"history", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"لُقّب السلطان سليمان بـ\"القانوني\" لإصلاحاته القانونية الواسعة في الدولة العثمانية." },

  // ==========================================
  // ---- الجغرافيا (GEOGRAPHY - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"ما هي عاصمة فرنسا؟", option1:"مدريد", option2:"باريس", option3:"روما", option4:"برلين", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"باريس هي عاصمة فرنسا وأكبر مدنها." },
  { question:"ما هو أكبر محيط في العالم من حيث المساحة؟", option1:"المحيط الأطلسي", option2:"المحيط الهندي", option3:"المحيط الهادئ", option4:"المحيط المتجمد الشمالي", correct_answer:3, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"المحيط الهادئ هو الأكبر مساحة بين محيطات الأرض." },
  { question:"في أي قارة تقع صحراء الصحراء الكبرى؟", option1:"آسيا", option2:"أفريقيا", option3:"أستراليا", option4:"أوروبا", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تمتد الصحراء الكبرى عبر شمال قارة أفريقيا." },
  { question:"ما هي عاصمة جمهورية مصر العربية؟", option1:"الإسكندرية", option2:"القاهرة", option3:"الجيزة", option4:"الأقصر", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"القاهرة هي عاصمة مصر وأكبر مدنها سكانًا." },
  { question:"ما هو أطول نهر في العالم بحسب معظم المصادر الجغرافية؟", option1:"نهر الأمازون", option2:"نهر النيل", option3:"نهر المسيسيبي", option4:"نهر دجلة", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُعد نهر النيل تقليديًا أطول أنهار العالم بطول يتجاوز 6600 كم." },
  { question:"كم عدد قارات العالم المعترف بها عادة؟", option1:"5", option2:"6", option3:"7", option4:"8", correct_answer:3, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُقسَّم العالم عادة إلى 7 قارات: آسيا وأفريقيا وأوروبا وأمريكا الشمالية وأمريكا الجنوبية وأستراليا وأنتاركتيكا." },
  { question:"ما اسم أعلى قمة جبلية في العالم؟", option1:"كليمنجارو", option2:"إفرست", option3:"جبال الألب", option4:"جبل فوجي", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"قمة إفرست في سلسلة الهيمالايا هي أعلى نقطة على سطح الأرض." },
  { question:"ما هي عاصمة اليابان؟", option1:"بكين", option2:"سيول", option3:"طوكيو", option4:"بانكوك", correct_answer:3, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"طوكيو هي عاصمة اليابان وأكبر تجمعاتها الحضرية." },
  { question:"أي دولة تُعرف تاريخيًا بأنها \"أرض الفراعنة\"؟", option1:"العراق", option2:"مصر", option3:"سوريا", option4:"اليمن", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"ارتبط لقب \"أرض الفراعنة\" بمصر لكونها موطن الحضارة الفرعونية القديمة." },
  { question:"ما اسم أكبر جزيرة في العالم؟", option1:"مدغشقر", option2:"جرينلاند", option3:"بورنيو", option4:"كوبا", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"جرينلاند هي أكبر جزيرة في العالم من حيث المساحة." },

  // متوسطة (10)
  { question:"ما هي عاصمة أستراليا؟", option1:"سيدني", option2:"ملبورن", option3:"كانبرا", option4:"بريزبن", correct_answer:3, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"كانبرا هي العاصمة الرسمية لأستراليا، رغم شهرة سيدني الأكبر." },
  { question:"أي دولة تضم حاليًا أكبر عدد من سكان العالم؟", option1:"الصين", option2:"الهند", option3:"الولايات المتحدة", option4:"إندونيسيا", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تجاوزت الهند الصين لتصبح الدولة الأكثر سكانًا في العالم." },
  { question:"ما اسم المضيق الذي يفصل بين قارتي آسيا وأفريقيا عند مدخل البحر الأحمر الجنوبي؟", option1:"مضيق هرمز", option2:"مضيق باب المندب", option3:"مضيق جبل طارق", option4:"مضيق البسفور", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يربط مضيق باب المندب البحر الأحمر بخليج عدن بين اليمن وجيبوتي." },
  { question:"ما هي أصغر دولة مستقلة في العالم من حيث المساحة؟", option1:"موناكو", option2:"سان مارينو", option3:"دولة الفاتيكان", option4:"ليختنشتاين", correct_answer:3, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"دولة الفاتيكان هي أصغر دولة مستقلة في العالم بمساحة أقل من نصف كيلومتر مربع." },
  { question:"في أي دولة عربية تقع مدينة البتراء الأثرية المنحوتة في الصخر؟", option1:"مصر", option2:"الأردن", option3:"لبنان", option4:"سوريا", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تقع مدينة البتراء الأثرية جنوب الأردن." },
  { question:"ما اسم السلسلة الجبلية التي تُعد الخط الفاصل تقليديًا بين قارتي أوروبا وآسيا؟", option1:"جبال الألب", option2:"جبال الأورال", option3:"جبال الهيمالايا", option4:"جبال الأنديز", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُستخدم جبال الأورال في روسيا كخط فاصل جغرافي تقليدي بين أوروبا وآسيا." },
  { question:"أي محيط يقع بين قارتي أمريكا الشمالية والجنوبية من جهة وأوروبا وأفريقيا من جهة أخرى؟", option1:"المحيط الهادئ", option2:"المحيط الأطلسي", option3:"المحيط الهندي", option4:"المحيط المتجمد الجنوبي", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يفصل المحيط الأطلسي بين قارتي الأمريكتين وأوروبا وأفريقيا." },
  { question:"ما هي العاصمة الرسمية لكندا؟", option1:"تورونتو", option2:"أوتاوا", option3:"فانكوفر", option4:"مونتريال", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"أوتاوا هي العاصمة الفيدرالية لكندا، رغم أن تورونتو أكبر مدنها." },
  { question:"ما اسم أكبر صحراء باردة في العالم؟", option1:"صحراء غوبي", option2:"القارة القطبية الجنوبية (أنتاركتيكا)", option3:"صحراء كالاهاري", option4:"الربع الخالي", correct_answer:2, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُصنَّف أنتاركتيكا جغرافيًا كأكبر صحراء باردة في العالم لقلة هطول الأمطار فيها." },
  { question:"ما هي الدولة العربية الوحيدة التي تمتد أراضيها على قارتين (آسيا وأفريقيا)؟", option1:"مصر", option2:"السعودية", option3:"الأردن", option4:"العراق", correct_answer:1, category:"geography", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تقع شبه جزيرة سيناء في مصر ضمن قارة آسيا، بينما تقع بقية أراضيها في أفريقيا." },

  // صعبة (10)
  { question:"ما هي أعمق نقطة معروفة في محيطات العالم؟", option1:"خندق ماريانا", option2:"خندق بورتوريكو", option3:"خندق تونغا", option4:"خندق كيرمديك", correct_answer:1, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يصل عمق خندق ماريانا في المحيط الهادئ إلى نحو 11 ألف متر." },
  { question:"أي دولة أظهرت مسوحات رسمية حديثة أنها تمتلك أكبر عدد مسجّل من الجزر في العالم؟", option1:"السويد", option2:"إندونيسيا", option3:"الفلبين", option4:"النرويج", correct_answer:1, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"كشف مسح وطني سويدي حديث عن وجود أكثر من 267 ألف جزيرة ضمن أراضي السويد." },
  { question:"ما اسم خط الطول الذي يُعتبر نقطة الصفر لحساب التوقيت العالمي؟", option1:"خط الاستواء", option2:"خط غرينتش", option3:"مدار السرطان", option4:"خط التاريخ الدولي", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُستخدم خط غرينتش في لندن كنقطة مرجعية لحساب التوقيت العالمي (GMT)." },
  { question:"أي الدول التالية محاطة بالكامل بأراضي دولة واحدة أخرى (جنوب أفريقيا)؟", option1:"ليسوتو", option2:"سويسرا", option3:"النمسا", option4:"البرتغال", correct_answer:1, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"مملكة ليسوتو محاطة بالكامل بأراضي جمهورية جنوب أفريقيا." },
  { question:"ما هي عاصمة كازاخستان؟", option1:"ألماتي", option2:"أستانا", option3:"بيشكك", option4:"طشقند", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أستانا هي العاصمة الرسمية لكازاخستان، بينما كانت ألماتي العاصمة سابقًا." },
  { question:"أي بحر يُعرف بأنه الأكثر ملوحة على وجه الأرض تقريبًا ولا تكاد توجد فيه حياة بحرية؟", option1:"البحر الأحمر", option2:"البحر الميت", option3:"بحر قزوين", option4:"البحر الأسود", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"ترتفع نسبة الملوحة في البحر الميت بشدة لدرجة تمنع بقاء معظم الكائنات البحرية فيه." },
  { question:"ما هي أكبر بحيرة عذبة في العالم من حيث المساحة السطحية؟", option1:"بحيرة فيكتوريا", option2:"بحيرة سوبيريور", option3:"بحيرة بايكال", option4:"البحر الميت", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"بحيرة سوبيريور في أمريكا الشمالية هي الأكبر مساحة سطحية بين البحيرات العذبة." },
  { question:"ما اسم خط العرض الذي يقسم الكرة الأرضية إلى نصفين شمالي وجنوبي متساويين تقريبًا؟", option1:"مدار السرطان", option2:"خط الاستواء", option3:"مدار الجدي", option4:"الدائرة القطبية الشمالية", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"خط الاستواء يقسم الأرض إلى نصفين كرويين شمالي وجنوبي." },
  { question:"ما اسم القناة الاصطناعية التي تربط البحر الأبيض المتوسط بالبحر الأحمر؟", option1:"قناة بنما", option2:"قناة السويس", option3:"قناة كورنث", option4:"مضيق ملقا", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تربط قناة السويس المصرية بين البحرين المتوسط والأحمر منذ افتتاحها عام 1869." },
  { question:"أي دولة تمتد أراضيها على أكبر عدد من المناطق الزمنية في العالم؟", option1:"الولايات المتحدة", option2:"روسيا", option3:"الصين", option4:"كندا", correct_answer:2, category:"geography", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تمتد روسيا على 11 منطقة زمنية، أكثر من أي دولة أخرى في العالم." },

  // ==========================================
  // ---- ثقافة عامة (CULTURE - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"كم عدد أيام الأسبوع؟", option1:"5", option2:"6", option3:"7", option4:"8", correct_answer:3, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يتكون الأسبوع من 7 أيام." },
  { question:"ما هو اللون الناتج عن مزج اللونين الأزرق والأصفر؟", option1:"الأحمر", option2:"الأخضر", option3:"البنفسجي", option4:"البرتقالي", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُنتج مزج الأزرق والأصفر اللون الأخضر." },
  { question:"ما هي العملة الرسمية للولايات المتحدة الأمريكية؟", option1:"اليورو", option2:"الدولار", option3:"الجنيه الإسترليني", option4:"الين", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الدولار الأمريكي هو العملة الرسمية للولايات المتحدة." },
  { question:"كم عدد أرجل العنكبوت؟", option1:"6", option2:"8", option3:"10", option4:"4", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"العناكب من فصيلة العنكبيات ولها 8 أرجل، بخلاف الحشرات ذات الست أرجل." },
  { question:"ما اسم الرياضة التي تُلعب بمضرب وريشة خفيفة فوق شبكة عالية؟", option1:"التنس", option2:"تنس الطاولة", option3:"الريشة الطائرة", option4:"الاسكواش", correct_answer:3, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تُلعب الريشة الطائرة (البادمنتون) بمضرب خفيف وريشة بدل الكرة." },
  { question:"ما اسم الشكل الهندسي الذي له ثلاثة أضلاع فقط؟", option1:"المربع", option2:"المثلث", option3:"الدائرة", option4:"المستطيل", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"المثلث شكل هندسي مكوّن من ثلاثة أضلاع وثلاث زوايا." },
  { question:"أي حيوان يُلقّب عادة بـ\"ملك الغابة\"؟", option1:"الفيل", option2:"الأسد", option3:"النمر", option4:"الدب", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُطلق على الأسد لقب ملك الغابة رمزًا لقوته وهيبته." },
  { question:"كم عدد الألوان الأساسية (الأولية) التي يمكن مزجها لتكوين معظم الألوان الأخرى؟", option1:"2", option2:"3", option3:"4", option4:"5", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الألوان الأساسية الثلاثة هي الأحمر والأزرق والأصفر." },
  { question:"ما اسم الآلة الموسيقية العربية ذات الصندوق الخشبي والأوتار التي تُعزف بالنقر أو الريشة؟", option1:"العود", option2:"الكمان", option3:"الطبلة", option4:"الناي", correct_answer:1, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"العود من أشهر الآلات الوترية التقليدية في الموسيقى العربية." },
  { question:"ما هو أكبر عضو حسي يغطي جسم الإنسان بالكامل؟", option1:"العين", option2:"الجلد", option3:"الأذن", option4:"الأنف", correct_answer:2, category:"culture", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الجلد هو أكبر أعضاء جسم الإنسان مساحة، ويعمل أيضًا كعضو حسي للمس." },

  // متوسطة (10)
  { question:"من هو الفنان الإيطالي الذي رسم لوحة \"الموناليزا\" الشهيرة؟", option1:"بابلو بيكاسو", option2:"ليوناردو دافينشي", option3:"فينسنت فان جوخ", option4:"مايكل أنجلو", correct_answer:2, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"رسم ليوناردو دافينشي لوحة الموناليزا في أوائل القرن السادس عشر." },
  { question:"ما اسم الجائزة العالمية المرموقة التي تُمنح سنويًا في مجالات كالسلام والأدب والعلوم؟", option1:"جائزة نوبل", option2:"جائزة الأوسكار", option3:"جائزة بوليتزر", option4:"جائزة غرامي", correct_answer:1, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"أسس ألفريد نوبل جائزة نوبل التي تُمنح في عدة مجالات منها السلام والأدب والعلوم." },
  { question:"من هو مؤلف المسرحية الشهيرة \"روميو وجولييت\"؟", option1:"تشارلز ديكنز", option2:"ويليام شكسبير", option3:"مارك توين", option4:"أوسكار وايلد", correct_answer:2, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"كتب الأديب الإنجليزي ويليام شكسبير مسرحية روميو وجولييت الشهيرة." },
  { question:"ما هي اللغة الرسمية الأكثر انتشارًا في البرازيل؟", option1:"الإسبانية", option2:"البرتغالية", option3:"الفرنسية", option4:"الإنجليزية", correct_answer:2, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"البرتغالية هي اللغة الرسمية للبرازيل بسبب استعمارها من قبل البرتغال." },
  { question:"في أي متحف عالمي شهير بباريس تُعرض لوحة الموناليزا حاليًا؟", option1:"متحف اللوفر", option2:"متحف أورساي", option3:"مركز بومبيدو", option4:"متحف الشمع", correct_answer:1, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يستضيف متحف اللوفر في باريس لوحة الموناليزا منذ سنوات طويلة." },
  { question:"كم عدد لاعبي فريق كرة القدم الواحد على أرض الملعب في المباراة الرسمية؟", option1:"9", option2:"10", option3:"11", option4:"12", correct_answer:3, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يتكون فريق كرة القدم من 11 لاعبًا على أرض الملعب في وقت واحد." },
  { question:"في أي مدينة فرنسية يُقام سنويًا مهرجان \"كان\" السينمائي الشهير؟", option1:"باريس", option2:"كان", option3:"نيس", option4:"مرسيليا", correct_answer:2, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يُقام مهرجان كان السينمائي الدولي في مدينة كان الفرنسية." },
  { question:"ما اسم الآلة الموسيقية الخشبية التي تُعزف بالنفخ وتستخدم بكثرة في الموسيقى الشعبية العربية؟", option1:"الناي", option2:"البيانو", option3:"الغيتار", option4:"الطبلة", correct_answer:1, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الناي آلة نفخ خشبية تقليدية شائعة في الموسيقى الشرقية." },
  { question:"ما هو المصدر الأصلي لحكايات \"ألف ليلة وليلة\"؟", option1:"تراث شعبي جُمع من مصادر متعددة دون مؤلف واحد", option2:"نجيب محفوظ", option3:"ابن المقفع", option4:"الجاحظ", correct_answer:1, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"ألف ليلة وليلة مجموعة حكايات شعبية تراكمت عبر قرون ولا يُنسب تأليفها لشخص بعينه." },
  { question:"ما اسم الرقصة الشعبية التي اشتهرت بها الأرجنتين عالميًا؟", option1:"السامبا", option2:"التانغو", option3:"الفلامنكو", option4:"الفالس", correct_answer:2, category:"culture", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"التانغو رقصة شعبية نشأت في الأرجنتين وأصبحت رمزًا ثقافيًا عالميًا لها." },

  // صعبة (10)
  { question:"من هو الموسيقار الألماني الذي أكمل تأليف سيمفونيته التاسعة الشهيرة رغم فقدانه السمع بالكامل؟", option1:"فولفغانغ موتسارت", option2:"لودفيغ فان بيتهوفن", option3:"يوهان سباستيان باخ", option4:"تشايكوفسكي", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"ألّف بيتهوفن سيمفونيته التاسعة وهو أصمّ تمامًا، وتُعد من أعظم الأعمال الموسيقية الكلاسيكية." },
  { question:"إلى أي حركة فنية ينتمي الرسام سلفادور دالي المعروف بلوحاته الغرائبية والحالمة؟", option1:"الانطباعية", option2:"السريالية", option3:"التكعيبية", option4:"الواقعية", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُعد دالي من أبرز رموز الحركة السريالية في الفن التشكيلي." },
  { question:"من هو الشاعر اليوناني القديم الذي تُنسب إليه ملحمتا \"الإلياذة\" و\"الأوديسة\"؟", option1:"أفلاطون", option2:"هوميروس", option3:"سقراط", option4:"أرسطو", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُنسب الملحمتان الإغريقيتان الشهيرتان تقليديًا إلى الشاعر هوميروس." },
  { question:"ما اسم الجائزة السينمائية الأمريكية التي يرمز إليها تمثال ذهبي صغير ويُطلق عليها أحيانًا اسم غير رسمي؟", option1:"غولدن غلوب", option2:"الأوسكار", option3:"بافتا", option4:"مهرجان كان", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تمنحها أكاديمية الفنون والعلوم السينمائية سنويًا، ويرمز إليها تمثال ذهبي معروف باسم \"الأوسكار\"." },
  { question:"من هو الرسام الهولندي الذي رسم لوحة \"ليلة النجوم\" الشهيرة وعانى من اضطرابات نفسية حادة؟", option1:"رامبرانت", option2:"فينسنت فان جوخ", option3:"يوهانس فيرمير", option4:"كلود مونيه", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"رسم فان جوخ لوحته الشهيرة \"ليلة النجوم\" خلال فترة علاجه في مصحة نفسية بفرنسا." },
  { question:"ما اسم النظام الموسيقي العربي التقليدي القائم على مجموعات نغمية تُعرف باسم واحد مميز؟", option1:"السلم الموسيقي الغربي", option2:"المقام العربي", option3:"النوتة الموسيقية", option4:"الكونشيرتو", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يعتمد المقام العربي على تسلسلات نغمية محددة تمنح الموسيقى الشرقية طابعها المميز." },
  { question:"من هو الكاتب الروسي الذي ألّف رواية \"الحرب والسلام\" الملحمية؟", option1:"فيودور دوستويفسكي", option2:"ليو تولستوي", option3:"أنطون تشيخوف", option4:"ألكسندر بوشكين", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"كتب ليو تولستوي رواية الحرب والسلام، وهي من أعظم الروايات في الأدب العالمي." },
  { question:"ما اسم الطراز المعماري الأوروبي الذي تشتهر به الكاتدرائيات بأقواسها المدببة ونوافذها الزجاجية الملونة؟", option1:"الطراز الروماني", option2:"الطراز القوطي", option3:"طراز الباروك", option4:"الطراز الكلاسيكي", correct_answer:2, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يتميز الطراز القوطي بالأقواس المدببة والزجاج الملون في كاتدرائيات القرون الوسطى." },
  { question:"من هو المخترع الألماني الذي طوّر آلة الطباعة ذات الحروف المتحركة في أوروبا؟", option1:"يوهانس غوتنبرغ", option2:"ليوناردو دافينشي", option3:"توماس إديسون", option4:"إسحاق نيوتن", correct_answer:1, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أحدث غوتنبرغ ثورة في نشر المعرفة باختراعه آلة الطباعة في منتصف القرن الخامس عشر." },
  { question:"ما اسم الملحمة الفارسية الشهيرة التي ألّفها الشاعر الفردوسي وتروي تاريخ الملوك الأسطوري لبلاد فارس؟", option1:"الشاهنامة", option2:"كليلة ودمنة", option3:"ديوان حافظ", option4:"المثنوي", correct_answer:1, category:"culture", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استغرق الفردوسي عقودًا لتأليف الشاهنامة، وتُعد من أعظم الملاحم الشعرية الفارسية." },

  // ==========================================
  // ---- جسم الإنسان (BODY - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"كم عدد الحواس الأساسية لدى الإنسان؟", option1:"3", option2:"4", option3:"5", option4:"6", correct_answer:3, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الحواس الخمس الأساسية هي البصر والسمع والشم والتذوق واللمس." },
  { question:"ما هو العضو المسؤول عن ضخّ الدم في جسم الإنسان؟", option1:"الرئة", option2:"القلب", option3:"الكبد", option4:"المعدة", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يضخّ القلب الدم عبر الأوعية الدموية إلى جميع أنحاء الجسم." },
  { question:"أي عضو نستخدمه لرؤية الأشياء من حولنا؟", option1:"الأذن", option2:"العين", option3:"الأنف", option4:"الجلد", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"العين هي عضو الإبصار المسؤول عن استقبال الضوء وتكوين الرؤية." },
  { question:"كم عدد أصابع اليد الواحدة عند الإنسان؟", option1:"4", option2:"5", option3:"6", option4:"10", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تحتوي كل يد على 5 أصابع." },
  { question:"ما اسم العضو المسؤول عن عملية التنفس في جسم الإنسان؟", option1:"القلب", option2:"الرئتان", option3:"الكلى", option4:"المعدة", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تقوم الرئتان بتبادل الأكسجين وثاني أكسيد الكربون مع الهواء." },
  { question:"أي جزء من الجسم نستخدمه بشكل أساسي للمشي؟", option1:"اليدان", option2:"الرجلان", option3:"الرأس", option4:"الأذنان", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تحمل الرجلان جسم الإنسان وتُمكّنانه من المشي والحركة." },
  { question:"ما اسم السائل الأحمر الذي يجري داخل الأوعية الدموية في جسم الإنسان؟", option1:"الماء", option2:"الدم", option3:"اللعاب", option4:"العرق", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"ينقل الدم الأكسجين والغذاء إلى خلايا الجسم عبر الأوعية الدموية." },
  { question:"أي عضو نستخدمه للسمع؟", option1:"العين", option2:"الأذن", option3:"الأنف", option4:"الفم", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الأذن هي العضو المسؤول عن التقاط الأصوات وتحويلها لإشارات يفهمها الدماغ." },
  { question:"ما اسم الغطاء الخارجي الذي يحمي جسم الإنسان بالكامل؟", option1:"العظام", option2:"الجلد", option3:"الشعر", option4:"الأظافر", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الجلد هو أكبر أعضاء الجسم ويعمل كحاجز واقٍ خارجي." },
  { question:"كم عدد العينين لدى الإنسان في الوضع الطبيعي؟", option1:"1", option2:"2", option3:"3", option4:"4", correct_answer:2, category:"body", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يمتلك الإنسان عينين تساعدانه على الرؤية بشكل مجسّم." },

  // متوسطة (10)
  { question:"كم يبلغ عدد عظام جسم الإنسان البالغ تقريبًا؟", option1:"106", option2:"206", option3:"306", option4:"406", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يحتوي جسم الإنسان البالغ على 206 عظمة تقريبًا." },
  { question:"ما اسم أكبر عضو في جسم الإنسان من حيث المساحة؟", option1:"الكبد", option2:"الجلد", option3:"الدماغ", option4:"الرئة", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الجلد هو أكبر أعضاء جسم الإنسان مساحةً ووزنًا." },
  { question:"أي جزء من الدماغ يُعد مسؤولاً بشكل أساسي عن التوازن والتنسيق الحركي؟", option1:"المخ", option2:"المخيخ", option3:"جذع الدماغ", option4:"الفص الجبهي", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"ينسّق المخيخ حركات الجسم ويحافظ على توازنه." },
  { question:"ما هو العضو المسؤول عن تنقية الدم من الفضلات وطرحها عبر البول؟", option1:"الكبد", option2:"الكليتان", option3:"الطحال", option4:"المعدة", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُرشّح الكليتان الدم وتزيلان الفضلات على شكل بول." },
  { question:"كم عدد فصوص الرئة اليمنى عند الإنسان عادة؟", option1:"2", option2:"3", option3:"4", option4:"1", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تتكون الرئة اليمنى من ثلاثة فصوص، بينما تتكون اليسرى من فصّين فقط." },
  { question:"ما اسم الهرمون المسؤول عن خفض مستوى السكر في الدم؟", option1:"الأدرينالين", option2:"الإنسولين", option3:"الثيروكسين", option4:"الميلاتونين", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يفرز البنكرياس الإنسولين لتنظيم مستوى السكر في الدم." },
  { question:"أي نوع من الأسنان يُستخدم أساسًا لتقطيع الطعام؟", option1:"الأنياب", option2:"القواطع", option3:"الأضراس", option4:"الضواحك", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"القواطع الأمامية مسطحة وحادة، مخصصة لتقطيع الطعام." },
  { question:"ما اسم الأنبوب العضلي الذي يربط الفم بالمعدة وينقل الطعام؟", option1:"القصبة الهوائية", option2:"المريء", option3:"الحنجرة", option4:"الأمعاء الدقيقة", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يدفع المريء الطعام من الفم إلى المعدة عبر انقباضات عضلية." },
  { question:"كم عدد حجرات القلب البشري؟", option1:"2", option2:"3", option3:"4", option4:"5", correct_answer:3, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يتكون القلب من أربع حجرات: أذينان وبطينان." },
  { question:"ما اسم خلايا الدم المسؤولة أساسًا عن مقاومة العدوى والدفاع عن الجسم؟", option1:"خلايا الدم الحمراء", option2:"خلايا الدم البيضاء", option3:"الصفائح الدموية", option4:"الخلايا العصبية", correct_answer:2, category:"body", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُشكّل خلايا الدم البيضاء خط الدفاع الأول لجهاز المناعة." },

  // صعبة (10)
  { question:"ما هي الوحدة الوظيفية الأساسية داخل الكلية والمسؤولة عن ترشيح الدم؟", option1:"النيفرون", option2:"الخلية العصبية", option3:"الحويصلة الهوائية", option4:"الغدة", correct_answer:1, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يحتوي كل كلية على نحو مليون نيفرون مسؤول عن ترشيح الدم وتكوين البول." },
  { question:"كم عدد أزواج الكروموسومات الموجودة في الخلية الجسدية البشرية العادية؟", option1:"22 زوجًا", option2:"23 زوجًا", option3:"24 زوجًا", option4:"25 زوجًا", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تحتوي الخلية الجسدية البشرية على 23 زوجًا من الكروموسومات، أي 46 كروموسومًا." },
  { question:"ما اسم الغدة التي تُلقَّب بـ\"الغدة الرئيسية\" لتحكّمها في نشاط معظم الغدد الصماء الأخرى؟", option1:"الغدة الدرقية", option2:"الغدة النخامية", option3:"الغدة الكظرية", option4:"البنكرياس", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُنظّم الغدة النخامية إفراز هرمونات معظم الغدد الصماء الأخرى في الجسم." },
  { question:"أي جزء من العين مسؤول عن التحكم في كمية الضوء الداخلة إليها؟", option1:"القرنية", option2:"القزحية والبؤبؤ", option3:"الشبكية", option4:"عدسة العين", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تتوسع القزحية وتنقبض لتضبط حجم البؤبؤ وكمية الضوء الداخلة للعين." },
  { question:"ما اسم البروتين الموجود في خلايا الدم الحمراء والمسؤول عن نقل الأكسجين؟", option1:"الكولاجين", option2:"الهيموغلوبين", option3:"الإنسولين", option4:"الميوغلوبين", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يرتبط الأكسجين بالهيموغلوبين لينتقل عبر الدم إلى أنسجة الجسم." },
  { question:"أي فصائل الدم التالية تُعرف بأنها \"المعطي العام\" الذي يمكن نقله لمعظم فصائل الدم الأخرى؟", option1:"AB+", option2:"O سالب", option3:"A موجب", option4:"B سالب", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"لا تحمل فصيلة O السالبة مولّدات مضادة، ما يجعلها آمنة نسبيًا للنقل لمعظم الفصائل الأخرى." },
  { question:"أي عضلات جسم الإنسان تُعتبر الأقوى نسبةً إلى حجمها الصغير؟", option1:"عضلة الفخذ", option2:"عضلة الفك (الماضغة)", option3:"عضلات البطن", option4:"عضلة الذراع", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُطبّق عضلة الفك الماضغة قوة كبيرة جدًا مقارنة بحجمها الصغير نسبيًا." },
  { question:"ما اسم الجزء من الجهاز العصبي الذي يربط الدماغ بباقي أجزاء الجسم عبر العمود الفقري؟", option1:"الأعصاب الطرفية", option2:"الحبل الشوكي", option3:"المخيخ", option4:"الغدة النخامية", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"ينقل الحبل الشوكي الإشارات العصبية بين الدماغ وبقية أعضاء الجسم." },
  { question:"كم يستغرق الدم تقريبًا لإكمال دورة كاملة في جسم الإنسان أثناء الراحة؟", option1:"جزء من الثانية", option2:"حوالي دقيقة واحدة", option3:"حوالي ساعة كاملة", option4:"يوم كامل", correct_answer:2, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يستغرق الدم في حالة الراحة نحو دقيقة واحدة لإتمام دورة كاملة عبر الجسم." },
  { question:"ما اسم العملية التي ينتج بها الجهاز المناعي أجسامًا مضادة استجابة للقاح أو عدوى سابقة؟", option1:"الاستجابة المناعية", option2:"الهضم", option3:"التنفس الخلوي", option4:"البناء الضوئي", correct_answer:1, category:"body", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُنتج الاستجابة المناعية أجسامًا مضادة تحمي الجسم عند التعرض للمسبب نفسه لاحقًا." },

  // ==========================================
  // ---- الرياضة (SPORTS - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"كم عدد لاعبي فريق كرة السلة على أرض الملعب في الوقت نفسه؟", option1:"5", option2:"6", option3:"7", option4:"11", correct_answer:1, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يتكون فريق كرة السلة من 5 لاعبين على أرض الملعب من كل جانب." },
  { question:"في أي رياضة يُستخدم مضرب وكرة صفراء صغيرة فوق شبكة فاصلة؟", option1:"كرة القدم", option2:"التنس", option3:"كرة السلة", option4:"الكريكيت", correct_answer:2, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُلعب التنس بمضارب وكرة صغيرة فوق شبكة تفصل بين اللاعبين." },
  { question:"كل كم سنة تُقام الألعاب الأولمبية الصيفية عادة؟", option1:"سنتان", option2:"3 سنوات", option3:"4 سنوات", option4:"5 سنوات", correct_answer:3, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تُقام الألعاب الأولمبية الصيفية كل 4 سنوات." },
  { question:"ما اسم الرياضة الشتوية التي تُلعب على الجليد بمضارب ويُسجَّل فيها بإدخال قرص داخل مرمى؟", option1:"كرة القدم", option2:"الهوكي على الجليد", option3:"السباحة", option4:"الجمباز", correct_answer:2, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تُلعب الهوكي على الجليد بمضارب معقوفة وقرص صغير يُسمى \"البك\"." },
  { question:"كم شوطًا في مباراة كرة القدم الرسمية؟", option1:"1", option2:"2", option3:"3", option4:"4", correct_answer:2, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تنقسم مباراة كرة القدم إلى شوطين، كل منهما 45 دقيقة." },
  { question:"ما لون البطاقة التي يُطرد بها لاعب كرة القدم نهائيًا من المباراة؟", option1:"الصفراء", option2:"الحمراء", option3:"الخضراء", option4:"الزرقاء", correct_answer:2, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تعني البطاقة الحمراء طرد اللاعب فورًا من المباراة." },
  { question:"ما اسم الرياضة الأولمبية التي تجمع بين السباحة وركوب الدراجة والجري؟", option1:"الترياثلون", option2:"الديكاثلون", option3:"البنتاثلون", option4:"رمي الكرة الحديدية", correct_answer:1, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يجمع الترياثلون بين السباحة وركوب الدراجات والجري في سباق واحد متتابع." },
  { question:"كم عدد الحلقات المتشابكة في الرمز الأولمبي؟", option1:"3", option2:"4", option3:"5", option4:"6", correct_answer:3, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يرمز الشعار الأولمبي بخمس حلقات إلى القارات الخمس المشاركة." },
  { question:"في أي رياضة يُستخدم مصطلح \"نوكاوت\" للفوز بضربة قاضية؟", option1:"الملاكمة", option2:"الجمباز", option3:"السباحة", option4:"الجولف", correct_answer:1, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"النوكاوت مصطلح شائع في رياضة الملاكمة يعني إسقاط الخصم وعدم قدرته على المتابعة." },
  { question:"ما اسم الكأس التي يحصل عليها الفائز ببطولة كأس العالم لكرة القدم؟", option1:"كأس أبطال أوروبا", option2:"كأس العالم لكرة القدم (FIFA)", option3:"الكرة الذهبية", option4:"كأس السوبر", correct_answer:2, category:"sports", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يحصل بطل المونديال على كأس العالم الرسمية الصادرة عن الفيفا." },

  // متوسطة (10)
  { question:"من هو أول سائق في تاريخ الفورمولا 1 يفوز بسبع بطولات عالم؟", option1:"لويس هاميلتون", option2:"مايكل شوماخر", option3:"نيكي لاودا", option4:"أيرتون سينا", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"كان مايكل شوماخر أول من حقق سبعة ألقاب عالمية في الفورمولا 1 عام 2004." },
  { question:"أي دولة استضافت نهائيات كأس العالم لكرة القدم عام 2018؟", option1:"البرازيل", option2:"روسيا", option3:"قطر", option4:"ألمانيا", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"استضافت روسيا بطولة كأس العالم لكرة القدم عام 2018." },
  { question:"كم عدد الحفر (الخانات) في جولة الغولف القياسية الكاملة؟", option1:"9", option2:"12", option3:"18", option4:"24", correct_answer:3, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تتكون جولة الغولف الرسمية الكاملة من 18 حفرة." },
  { question:"ما هو الاسم الشائع للبطولات الأربع الكبرى في التنس التي من بينها ويمبلدون؟", option1:"البطولات الكبرى (الجراند سلام)", option2:"بطولات الماسترز", option3:"دوري الأبطال", option4:"الكأس الذهبية", correct_answer:1, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تشمل بطولات الجراند سلام أستراليا المفتوحة ورولان غاروس وويمبلدون وأمريكا المفتوحة." },
  { question:"في أي رياضات قتالية يُستخدم مصطلح \"الحزام الأسود\" كأعلى مستوى إتقان؟", option1:"الملاكمة", option2:"فنون الدفاع عن النفس كالكاراتيه والجودو", option3:"السباحة", option4:"الرماية", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يرمز الحزام الأسود في الفنون القتالية اليابانية والكورية لأعلى درجات الإتقان." },
  { question:"أي منتخب فاز بأكبر عدد من بطولات كأس العالم لكرة القدم حتى الآن؟", option1:"ألمانيا", option2:"الأرجنتين", option3:"إيطاليا", option4:"البرازيل", correct_answer:4, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"فاز منتخب البرازيل بكأس العالم خمس مرات، وهو الرقم الأعلى حتى الآن." },
  { question:"ما اسم أشهر سباق دراجات هوائية سنوي يُقام في فرنسا؟", option1:"جيرو ديطاليا", option2:"تور دي فرانس", option3:"فويلتا إسبانيا", option4:"باريس روبيه", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يُعد تور دي فرانس من أعرق وأشهر سباقات الدراجات الهوائية في العالم." },
  { question:"كم عدد الأشواط (الجولات) في مباراة الملاكمة الاحترافية القياسية عادةً؟", option1:"6 جولات", option2:"10 جولات", option3:"12 جولة", option4:"15 جولة", correct_answer:3, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تتكون مباريات ألقاب الملاكمة الاحترافية الرسمية من 12 جولة." },
  { question:"ما اسم الرياضة الأولمبية التي تجمع بين الرماية وركوب الخيل والمبارزة والسباحة والجري في مسابقة واحدة؟", option1:"الترياثلون", option2:"البنتاثلون الحديث", option3:"الديكاثلون", option4:"السباعي", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يجمع البنتاثلون الحديث بين خمس رياضات مختلفة في مسابقة أولمبية واحدة." },
  { question:"من هو اللاعب الأرجنتيني الذي سجّل هدف \"يد الله\" الشهير أمام إنجلترا عام 1986؟", option1:"بيليه", option2:"دييغو مارادونا", option3:"فرانز بيكنباور", option4:"يوهان كرويف", correct_answer:2, category:"sports", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"سجّل مارادونا هدفه المثير للجدل بيده في ربع نهائي مونديال 1986." },

  // صعبة (10)
  { question:"من هو صاحب الرقم القياسي العالمي الحالي في سباق 100 متر عدو للرجال؟", option1:"كارل لويس", option2:"يوسين بولت", option3:"أسافا باول", option4:"تايسون غاي", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"سجّل العدّاء الجامايكي يوسين بولت رقمًا قياسيًا عالميًا في سباق 100 متر لم يُكسر بعد." },
  { question:"أي منتخب فاز بأول نسخة من كأس العالم لكرة القدم عام 1930؟", option1:"البرازيل", option2:"الأوروغواي", option3:"الأرجنتين", option4:"إيطاليا", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استضافت الأوروغواي أول بطولة لكأس العالم عام 1930 وفازت بها أيضًا." },
  { question:"ما اسم الملعب الرئيسي الذي تُقام عليه نهائيات بطولة ويمبلدون للتنس؟", option1:"ملعب آرثر آش", option2:"الملعب المركزي بويمبلدون", option3:"ملعب رولان غاروس", option4:"ملعب رود لايفر", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُقام النهائي الرئيسي لبطولة ويمبلدون على \"الملعب المركزي\" التاريخي." },
  { question:"كم عدد الميداليات الذهبية الأولمبية التي حصدها السباح مايكل فيلبس عبر مسيرته الرياضية؟", option1:"18 ميدالية ذهبية", option2:"23 ميدالية ذهبية", option3:"15 ميدالية ذهبية", option4:"20 ميدالية ذهبية", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"حصد فيلبس 23 ميدالية ذهبية أولمبية، وهو رقم قياسي لم يقترب منه أحد." },
  { question:"من هو اللاعب الذي يحمل حاليًا الرقم القياسي لأكبر عدد أهداف مسجّلة في تاريخ نهائيات كأس العالم؟", option1:"بيليه", option2:"رونالدو نازاريو (البرازيلي)", option3:"ميروسلاف كلوزه", option4:"ليونيل ميسي", correct_answer:3, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"سجّل الألماني ميروسلاف كلوزه 16 هدفًا عبر مشاركاته في نهائيات كأس العالم، وهو الرقم القياسي حاليًا." },
  { question:"ما اسم البطولة القارية الأوروبية الرسمية لمنتخبات كرة القدم؟", option1:"دوري أبطال أوروبا", option2:"كأس الأمم الأوروبية (اليورو)", option3:"كأس الاتحاد الأوروبي", option4:"السوبر الأوروبي", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُقام بطولة اليورو كل 4 سنوات لمنتخبات القارة الأوروبية الوطنية." },
  { question:"في أي مدينة أُقيمت أول دورة ألعاب أولمبية حديثة عام 1896؟", option1:"باريس", option2:"أثينا", option3:"لندن", option4:"روما", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"احتضنت أثينا اليونانية أول دورة أولمبية حديثة عام 1896." },
  { question:"من هو الملاكم الأمريكي الملقّب بـ\"الأعظم\" والذي اشتهر بمقولاته الجريئة داخل الحلبة وخارجها؟", option1:"مايك تايسون", option2:"محمد علي كلاي", option3:"جورج فورمان", option4:"مانوي باكياو", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"لقّب محمد علي كلاي نفسه بـ\"الأعظم\" وأصبح من أشهر الملاكمين في التاريخ." },
  { question:"ما هو الاسم الرسمي للدوري الاحترافي الأمريكي لكرة السلة؟", option1:"NFL", option2:"NBA", option3:"MLB", option4:"NHL", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"NBA هي الرابطة الوطنية لكرة السلة الاحترافية في أمريكا الشمالية." },
  { question:"من هو اللاعب الحائز على أكبر عدد من جوائز \"الكرة الذهبية\" (Ballon d'Or) في تاريخ كرة القدم حتى الآن؟", option1:"كريستيانو رونالدو", option2:"ليونيل ميسي", option3:"بيليه", option4:"دييغو مارادونا", correct_answer:2, category:"sports", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"حصد ليونيل ميسي أكبر عدد من جوائز الكرة الذهبية الفردية بفارق واضح عن أقرب منافسيه." },

  // ==========================================
  // ---- الذكاء الاصطناعي (AI - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"ماذا يعني الاختصار AI الشائع في عالم التقنية؟", option1:"البرمجة الآلية", option2:"الذكاء الاصطناعي", option3:"الإنترنت السريع", option4:"التحليل الآلي", correct_answer:2, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"AI اختصار Artificial Intelligence، أي الذكاء الاصطناعي." },
  { question:"ما اسم المساعد الصوتي الذكي التابع لشركة أمازون؟", option1:"سيري", option2:"أليكسا", option3:"كورتانا", option4:"جوجل أسيستنت", correct_answer:2, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"أليكسا هو المساعد الصوتي الذكي الذي طوّرته شركة أمازون." },
  { question:"أي مما يلي يُعد مثالاً واضحًا على تطبيقات الذكاء الاصطناعي؟", option1:"الآلة الحاسبة العادية", option2:"روبوت المحادثة الذكي (Chatbot)", option3:"المسطرة", option4:"الساعة الميكانيكية", correct_answer:2, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"روبوتات المحادثة الذكية تعتمد على نماذج ذكاء اصطناعي لفهم اللغة والرد عليها." },
  { question:"ما اسم روبوت المحادثة الشهير التابع لشركة OpenAI؟", option1:"ChatGPT", option2:"Excel", option3:"Photoshop", option4:"Windows", correct_answer:1, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"ChatGPT نموذج ذكاء اصطناعي محادثي طوّرته شركة OpenAI." },
  { question:"هل يمكن لأنظمة الذكاء الاصطناعي الحديثة التعرّف على محتوى الصور؟", option1:"نعم", option2:"لا مطلقًا", option3:"فقط الصور بالأبيض والأسود", option4:"فقط صور الحيوانات", correct_answer:1, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تستطيع أنظمة الرؤية الحاسوبية المدعومة بالذكاء الاصطناعي تحليل محتوى الصور بدقة عالية." },
  { question:"ما هو الأساس الذي تتعلم منه أنظمة الذكاء الاصطناعي الحديثة؟", option1:"البيانات", option2:"الورق فقط", option3:"الكهرباء فقط", option4:"الصوت فقط", correct_answer:1, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تعتمد نماذج الذكاء الاصطناعي على كميات كبيرة من البيانات للتعلم واكتشاف الأنماط." },
  { question:"أي نوع من السيارات يعتمد على الذكاء الاصطناعي للتنقل دون تدخل بشري؟", option1:"السيارة العادية", option2:"السيارة ذاتية القيادة", option3:"الدراجة الهوائية", option4:"القطار البخاري القديم", correct_answer:2, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تستخدم السيارات ذاتية القيادة أنظمة ذكاء اصطناعي لتحليل الطريق واتخاذ القرارات." },
  { question:"ما اسم التقنية التي تُترجم النصوص بين اللغات آليًا بمساعدة الذكاء الاصطناعي؟", option1:"الترجمة الآلية", option2:"الطباعة اليدوية", option3:"الخط اليدوي", option4:"التدقيق الإملائي فقط", correct_answer:1, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تعتمد أدوات الترجمة الآلية الحديثة على نماذج ذكاء اصطناعي لفهم وترجمة النصوص." },
  { question:"هل تستطيع أنظمة الذكاء الاصطناعي الحديثة التعرّف على الأوامر الصوتية البشرية؟", option1:"نعم", option2:"لا إطلاقًا", option3:"فقط في الليل", option4:"فقط عند الأطفال", correct_answer:1, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تعتمد المساعدات الصوتية على تقنيات التعرف على الكلام المبنية على الذكاء الاصطناعي." },
  { question:"ما اسم المساعد الصوتي الذكي المدمج في أجهزة شركة آبل؟", option1:"أليكسا", option2:"سيري", option3:"كورتانا", option4:"بيكسل", correct_answer:2, category:"ai", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"سيري هو المساعد الصوتي الذكي المدمج في أجهزة آبل مثل آيفون." },

  // متوسطة (10)
  { question:"ما هو فرع الذكاء الاصطناعي الذي يُمكّن الأنظمة من التعلّم تلقائيًا من البيانات دون برمجة صريحة لكل حالة؟", option1:"تعلم الآلة", option2:"قواعد البيانات", option3:"الشبكات السلكية", option4:"البرمجة الكائنية التقليدية", correct_answer:1, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تعلم الآلة (Machine Learning) يتيح للنماذج تحسين أدائها تلقائيًا من خلال التعرض للبيانات." },
  { question:"ماذا تعني اختصار NLP في مجال الذكاء الاصطناعي؟", option1:"معالجة اللغة الطبيعية", option2:"الشبكات العصبية", option3:"التعلم العميق", option4:"الرؤية الحاسوبية", correct_answer:1, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تهتم معالجة اللغة الطبيعية (NLP) بتمكين الحاسوب من فهم وتوليد اللغة البشرية." },
  { question:"أي شركة طوّرت برنامج الشطرنج الشهير \"ديب بلو\" الذي هزم بطل العالم كاسباروف عام 1997؟", option1:"جوجل", option2:"IBM", option3:"مايكروسوفت", option4:"آبل", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"طوّرت شركة IBM حاسوب ديب بلو الذي هزم بطل الشطرنج غاري كاسباروف." },
  { question:"ما اسم نظام الذكاء الاصطناعي الذي هزم بطل العالم في لعبة \"غو\" الصينية عام 2016؟", option1:"ديب بلو", option2:"ألفاغو", option3:"واتسون", option4:"تاي", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"طوّرت شركة DeepMind نظام ألفاغو الذي تفوّق على بطل لعبة غو العالمي." },
  { question:"ما هو المقصود بمصطلح \"التعلم العميق\" (Deep Learning)؟", option1:"فرع من تعلم الآلة يعتمد على شبكات عصبية متعددة الطبقات", option2:"نوع من قواعد البيانات التقليدية", option3:"لغة برمجة حديثة", option4:"بروتوكول اتصال شبكي", correct_answer:1, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يعتمد التعلم العميق على شبكات عصبية اصطناعية متعددة الطبقات لمعالجة بيانات معقدة." },
  { question:"أي مما يلي يُعد مثالاً على الذكاء الاصطناعي التوليدي (Generative AI)؟", option1:"آلة حاسبة بسيطة", option2:"برنامج يولّد صورًا جديدة من وصف نصي", option3:"برنامج جداول بيانات تقليدي", option4:"متصفح إنترنت عادي", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"ينشئ الذكاء الاصطناعي التوليدي محتوى جديدًا كليًا كالصور والنصوص بدل تحليل بيانات موجودة فقط." },
  { question:"ما اسم الاختبار الذي اقترحه عالم الحاسوب آلان تورينج لتقييم مدى ذكاء الآلة؟", option1:"اختبار الذكاء العام IQ", option2:"اختبار تورينج", option3:"اختبار ستانفورد", option4:"اختبار بينيه", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"اقترح تورينج عام 1950 اختباره الشهير لتقييم قدرة الآلة على محاكاة السلوك الذكي البشري." },
  { question:"ما هو الغرض الأساسي من \"بيانات التدريب\" في عملية تعلم الآلة؟", option1:"تخزين الملفات فقط", option2:"تعليم النموذج التعرّف على الأنماط واتخاذ القرار", option3:"تسريع اتصال الإنترنت", option4:"حماية النظام من الفيروسات", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُستخدم بيانات التدريب لتعليم النموذج كيفية التعرف على الأنماط قبل استخدامه الفعلي." },
  { question:"أي فرع من فروع الذكاء الاصطناعي يُستخدم أساسًا للتعرّف على الوجوه داخل الصور؟", option1:"الرؤية الحاسوبية", option2:"معالجة اللغة الطبيعية", option3:"قواعد البيانات العلائقية", option4:"الشبكات اللاسلكية", correct_answer:1, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"تُعنى الرؤية الحاسوبية بتحليل وفهم محتوى الصور ومقاطع الفيديو، ومنها التعرف على الوجوه." },
  { question:"ما اسم الظاهرة التي يفشل فيها نموذج تعلم الآلة في التعميم بسبب حفظه لتفاصيل بيانات التدريب فقط؟", option1:"نقص التخصيص (Underfitting)", option2:"فرط التخصيص (Overfitting)", option3:"الانحدار الخطي", option4:"التصنيف الثنائي", correct_answer:2, category:"ai", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يحدث فرط التخصيص عندما يحفظ النموذج تفاصيل بيانات التدريب بدل تعلّم الأنماط العامة." },

  // صعبة (10)
  { question:"ما هي المعمارية العصبية التي تعتمد عليها معظم النماذج اللغوية الكبيرة الحديثة مثل GPT؟", option1:"الشبكات التلافيفية CNN", option2:"معمارية المحوّلات Transformer", option3:"الشبكات المتكررة RNN", option4:"الشبكات التوليدية التنافسية GAN", correct_answer:2, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تعتمد النماذج اللغوية الكبيرة الحديثة على معمارية المحوّلات (Transformer) وآلية الانتباه الذاتي." },
  { question:"ماذا يعني الاختصار GAN في مجال التعلم العميق؟", option1:"الشبكات التوليدية التنافسية", option2:"الشبكات العصبية الرسومية", option3:"خوارزمية البحث الجيني", option4:"نموذج تحليل البيانات الإحصائي", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تتكون شبكات GAN من شبكتين متنافستين (مولّد ومُميّز) لإنتاج بيانات واقعية جديدة." },
  { question:"من هو عالم الحاسوب الذي نظّم أول مؤتمر رسمي حول \"الذكاء الاصطناعي\" عام 1956 وصاغ المصطلح؟", option1:"آلان تورينج", option2:"جون مكارثي", option3:"مارفن مينسكي", option4:"نورمان ويبر", correct_answer:2, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُنسب لجون مكارثي تنظيم مؤتمر دارتموث 1956 وصياغة مصطلح \"الذكاء الاصطناعي\" رسميًا." },
  { question:"ما اسم الخوارزمية الأساسية المستخدمة لتحديث أوزان الشبكة العصبية أثناء التدريب بهدف تقليل الخطأ؟", option1:"الانحدار التدريجي (Gradient Descent)", option2:"الفرز السريع (Quick Sort)", option3:"البحث الثنائي", option4:"خوارزمية التجزئة", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُستخدم الانحدار التدريجي لتعديل أوزان النموذج تدريجيًا باتجاه تقليل دالة الخطأ." },
  { question:"ما هي تقنية RLHF التي استُخدمت لتحسين استجابات نماذج لغوية كبيرة مثل ChatGPT؟", option1:"التعلم المعزز من ملاحظات البشر", option2:"التعلم غير الخاضع للإشراف فقط", option3:"معالجة الصور الرقمية", option4:"ضغط الملفات وتقليل حجمها", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُستخدم التعلم المعزز من ملاحظات البشر (RLHF) لضبط استجابات النموذج لتكون أكثر فائدة وأمانًا." },
  { question:"ما اسم المشكلة التي تحدث عندما تتلاشى قيم الاشتقاق بشكل كبير أثناء تدريب شبكات عصبية عميقة جدًا؟", option1:"مشكلة الانحدار المتلاشي (Vanishing Gradient)", option2:"الانفجار الحسابي للذاكرة", option3:"فرط التخصيص", option4:"نقص البيانات التدريبية", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تُصعّب مشكلة الانحدار المتلاشي تدريب الطبقات الأولى في الشبكات العصبية العميقة جدًا." },
  { question:"أي مكتبة برمجية مفتوحة المصدر طوّرها فريق Google Brain لبناء نماذج التعلم العميق؟", option1:"PyTorch", option2:"TensorFlow", option3:"Scikit-learn", option4:"Pandas", correct_answer:2, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"طوّرت جوجل مكتبة TensorFlow المفتوحة المصدر لبناء وتدريب نماذج التعلم العميق." },
  { question:"ما هو الفرق الجوهري بين التعلم الخاضع للإشراف وغير الخاضع للإشراف في تعلم الآلة؟", option1:"وجود بيانات مُصنَّفة بمخرجات معروفة من عدمه", option2:"سرعة معالجة البيانات فقط", option3:"حجم البيانات المُستخدمة فقط", option4:"نوع لغة البرمجة المستخدمة", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يعتمد التعلم الخاضع للإشراف على بيانات ذات مخرجات معروفة مسبقًا، بخلاف غير الخاضع للإشراف." },
  { question:"ما اسم المصفوفة التي تُستخدم لتقييم أداء نموذج تصنيف عبر مقارنة التوقعات الصحيحة والخاطئة؟", option1:"مصفوفة الارتباك (Confusion Matrix)", option2:"مصفوفة الانحدار الخطي", option3:"الجدول المحوري", option4:"مخطط جانت", correct_answer:1, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تعرض مصفوفة الارتباك عدد التوقعات الصحيحة والخاطئة لكل فئة في نموذج التصنيف." },
  { question:"ما المقصود بمصطلح \"الانحياز الخوارزمي\" (Algorithmic Bias) في أنظمة الذكاء الاصطناعي؟", option1:"عطل في الدوائر الكهربائية للجهاز", option2:"ميل غير عادل في نتائج النموذج ناتج عن بيانات التدريب", option3:"نوع من تشفير البيانات", option4:"بروتوكول اتصال بين الخوادم", correct_answer:2, category:"ai", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"ينشأ الانحياز الخوارزمي غالبًا من بيانات تدريب غير متوازنة تعكس تحيّزات موجودة أصلاً." },

  // ==========================================
  // ---- الدين (RELIGION - 30 سؤال) ----
  // ==========================================
  // سهلة (10)
  { question:"كم عدد أركان الإسلام؟", option1:"3", option2:"4", option3:"5", option4:"6", correct_answer:3, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"أركان الإسلام خمسة: الشهادتان، الصلاة، الزكاة، الصوم، والحج." },
  { question:"ما هو الكتاب المقدس الذي أُنزل على النبي محمد ﷺ؟", option1:"التوراة", option2:"الإنجيل", option3:"القرآن الكريم", option4:"الزبور", correct_answer:3, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"القرآن الكريم هو الكتاب الذي أنزله الله على النبي محمد ﷺ." },
  { question:"كم عدد الصلوات المفروضة على المسلم في اليوم والليلة؟", option1:"3", option2:"4", option3:"5", option4:"6", correct_answer:3, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الصلوات الخمس المفروضة هي الفجر والظهر والعصر والمغرب والعشاء." },
  { question:"إلى أين يتّجه المسلمون في صلاتهم؟", option1:"المسجد الأقصى", option2:"الكعبة المشرفة", option3:"المسجد النبوي", option4:"جبل عرفة", correct_answer:2, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يتّجه المسلمون في صلاتهم نحو الكعبة المشرفة بمكة المكرمة." },
  { question:"في أي شهر هجري يُفرض صيام رمضان؟", option1:"شعبان", option2:"رمضان", option3:"شوال", option4:"ذو الحجة", correct_answer:2, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يُفرض الصيام في شهر رمضان، وهو الشهر التاسع من التقويم الهجري." },
  { question:"ما اسم أول سورة تُقرأ في المصحف الشريف؟", option1:"سورة البقرة", option2:"سورة الفاتحة", option3:"سورة الإخلاص", option4:"سورة الناس", correct_answer:2, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"سورة الفاتحة هي السورة الأولى في ترتيب المصحف." },
  { question:"من هو خاتم الأنبياء والمرسلين في الإسلام؟", option1:"عيسى عليه السلام", option2:"موسى عليه السلام", option3:"محمد ﷺ", option4:"إبراهيم عليه السلام", correct_answer:3, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"يعتقد المسلمون أن النبي محمدًا ﷺ هو خاتم الأنبياء والمرسلين." },
  { question:"ما اسم الشعيرة الدينية التي يؤديها المسلمون القادرون في مكة المكرمة مرة في العمر؟", option1:"الحج", option2:"صلاة الجمعة فقط", option3:"الزكاة", option4:"لا شيء مما سبق", correct_answer:1, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الحج ركن من أركان الإسلام يؤدّى في مكة المكرمة لمن استطاع إليه سبيلًا." },
  { question:"ما هما عيدا المسلمين الرسميان؟", option1:"عيد الفطر وعيد الأضحى", option2:"عيد المولد ورأس السنة", option3:"عيد الهجرة وعيد الفطر", option4:"عيد الأضحى فقط", correct_answer:1, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"عيدا المسلمين هما عيد الفطر بعد رمضان وعيد الأضحى في موسم الحج." },
  { question:"من هو أول الخلفاء الراشدين بعد وفاة النبي ﷺ؟", option1:"عمر بن الخطاب", option2:"أبو بكر الصديق", option3:"عثمان بن عفان", option4:"علي بن أبي طالب", correct_answer:2, category:"religion", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"تولى أبو بكر الصديق الخلافة أولاً بعد وفاة النبي محمد ﷺ." },

  // متوسطة (10)
  { question:"كم عدد سور القرآن الكريم؟", option1:"110", option2:"114", option3:"120", option4:"100", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يتكون القرآن الكريم من 114 سورة." },
  { question:"ما اسم الغار الذي نزل فيه الوحي على النبي ﷺ لأول مرة؟", option1:"غار ثور", option2:"غار حراء", option3:"غار أحد", option4:"غار الكهف", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"نزل الوحي على النبي ﷺ أول مرة في غار حراء بجبل النور قرب مكة." },
  { question:"ما هي أطول سورة في القرآن الكريم من حيث عدد الآيات؟", option1:"سورة آل عمران", option2:"سورة البقرة", option3:"سورة النساء", option4:"سورة المائدة", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"سورة البقرة هي أطول سور القرآن الكريم بـ 286 آية." },
  { question:"من هو النبي الذي التقمه الحوت بحسب القصص القرآني؟", option1:"يونس عليه السلام", option2:"يوسف عليه السلام", option3:"نوح عليه السلام", option4:"إلياس عليه السلام", correct_answer:1, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"قصة النبي يونس عليه السلام مع الحوت مذكورة في القرآن الكريم." },
  { question:"ما اسم الرحلة الليلية التي انتقل فيها النبي ﷺ من مكة إلى بيت المقدس ثم عُرج به إلى السماء؟", option1:"الهجرة النبوية", option2:"الإسراء والمعراج", option3:"فتح مكة", option4:"غزوة الخندق", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"الإسراء والمعراج رحلة معجزة نُقل فيها النبي ﷺ من المسجد الحرام إلى الأقصى ثم للسماء." },
  { question:"في أي سنة هجرية وقعت غزوة بدر الكبرى؟", option1:"السنة الأولى للهجرة", option2:"السنة الثانية للهجرة", option3:"السنة الخامسة للهجرة", option4:"السنة العاشرة للهجرة", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"وقعت غزوة بدر الكبرى في السنة الثانية للهجرة." },
  { question:"من هو النبي الذي بنى السفينة لينجو من الطوفان مع المؤمنين معه؟", option1:"نوح عليه السلام", option2:"هود عليه السلام", option3:"صالح عليه السلام", option4:"شعيب عليه السلام", correct_answer:1, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"أمر الله نبيه نوحًا عليه السلام ببناء السفينة لينجو من الطوفان." },
  { question:"ما اسم الملك الذي وكّله الله بنقل الوحي إلى الأنبياء؟", option1:"ميكائيل عليه السلام", option2:"جبريل عليه السلام", option3:"إسرافيل عليه السلام", option4:"عزرائيل عليه السلام", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"جبريل عليه السلام هو الملك الموكل بنقل الوحي إلى الأنبياء." },
  { question:"من هو الصحابي الذي لُقّب بـ\"سيف الله المسلول\" لبراعته العسكرية؟", option1:"عمر بن الخطاب", option2:"خالد بن الوليد", option3:"سعد بن أبي وقاص", option4:"أبو عبيدة بن الجراح", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"لقّب النبي ﷺ الصحابي خالد بن الوليد بـ\"سيف الله المسلول\"." },
  { question:"كم عدد أركان الإيمان في العقيدة الإسلامية؟", option1:"خمسة أركان", option2:"ستة أركان", option3:"أربعة أركان", option4:"سبعة أركان", correct_answer:2, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"أركان الإيمان ستة: الإيمان بالله وملائكته وكتبه ورسله واليوم الآخر والقدر خيره وشره." },

  // صعبة (10)
  { question:"ما هي السورة الوحيدة في القرآن الكريم التي لا تبدأ بالبسملة؟", option1:"سورة يونس", option2:"سورة التوبة", option3:"سورة النمل", option4:"سورة الأنفال", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"سورة التوبة هي السورة الوحيدة في المصحف التي لا تبدأ ببسم الله الرحمن الرحيم." },
  { question:"من هو الصحابي الذي كُلّف بجمع القرآن الكريم في مصحف واحد في عهد الخليفة عثمان بن عفان؟", option1:"زيد بن ثابت", option2:"أُبي بن كعب", option3:"عبدالله بن مسعود", option4:"معاذ بن جبل", correct_answer:1, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"تولى الصحابي زيد بن ثابت رئاسة لجنة توحيد المصحف في عهد عثمان بن عفان." },
  { question:"ما اسم أقصر سورة في القرآن الكريم من حيث عدد الآيات؟", option1:"سورة الإخلاص", option2:"سورة الكوثر", option3:"سورة النصر", option4:"سورة العصر", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"سورة الكوثر أقصر سور القرآن الكريم بثلاث آيات فقط." },
  { question:"إلى كم جزءًا يُقسَّم القرآن الكريم عادة لتيسير حفظه وتلاوته؟", option1:"20 جزءًا", option2:"30 جزءًا", option3:"40 جزءًا", option4:"60 جزءًا", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"يُقسَّم المصحف الشريف تقليديًا إلى 30 جزءًا." },
  { question:"من هو النبي الذي كلّمه الله مباشرة دون واسطة ولُقّب بـ\"كليم الله\"؟", option1:"إبراهيم عليه السلام", option2:"موسى عليه السلام", option3:"عيسى عليه السلام", option4:"آدم عليه السلام", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"خصّ الله نبيه موسى عليه السلام بالتكليم المباشر عند جبل الطور." },
  { question:"ما اسم المعركة التي انتصر فيها المسلمون على الفرس وأضعفت بشدة الإمبراطورية الساسانية؟", option1:"معركة القادسية", option2:"معركة اليرموك", option3:"معركة بدر", option4:"معركة أحد", correct_answer:1, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"أضعفت معركة القادسية قوة الإمبراطورية الساسانية الفارسية بشكل كبير." },
  { question:"من هو الصحابي الذي لُقّب بـ\"أمين هذه الأمة\" بحسب الحديث النبوي؟", option1:"أبو عبيدة بن الجراح", option2:"سعد بن أبي وقاص", option3:"معاذ بن جبل", option4:"أبو هريرة", correct_answer:1, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"ورد في الحديث النبوي أن أبا عبيدة بن الجراح هو أمين هذه الأمة." },
  { question:"في أي غزوة استُشهد حمزة بن عبدالمطلب، عم النبي ﷺ؟", option1:"غزوة بدر", option2:"غزوة أحد", option3:"غزوة الخندق", option4:"غزوة حنين", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استُشهد حمزة بن عبدالمطلب في غزوة أحد ولُقّب بأسد الله وأسد رسوله." },
  { question:"من هو الخليفة الراشد الذي استُشهد وهو يصلي في محراب مسجد الكوفة؟", option1:"عمر بن الخطاب", option2:"عثمان بن عفان", option3:"علي بن أبي طالب", option4:"أبو بكر الصديق", correct_answer:3, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استُشهد الخليفة علي بن أبي طالب أثناء صلاة الفجر في مسجد الكوفة." },
  { question:"كم استمرت فترة الدعوة الإسلامية السرية في مكة قبل أن يُؤمر النبي ﷺ بالجهر بها؟", option1:"سنة واحدة", option2:"ثلاث سنوات", option3:"خمس سنوات", option4:"عشر سنوات", correct_answer:2, category:"religion", age_min:14, age_max:99, difficulty:"hard", points:20, explanation:"استمرت الدعوة السرية في مكة نحو ثلاث سنوات قبل الأمر بالجهر بالدعوة." },

  // ==========================================
  // ---- أمثلة على الأنواع الجديدة: صح/خطأ، مطابقة، ترتيب ----
  // (الأسئلة أعلاه كلها اختيار من متعدد ولم تُمس إطلاقًا — هذه أمثلة
  // إضافية توضّح الأنواع الجديدة فقط، ويمكن للمشرف إضافة المزيد منها
  // أو حذفها من لوحة التحكم كأي سؤال آخر)
  // ==========================================

  // -- صح / خطأ (True/False) --
  { type:"true_false", question:"تدور الأرض حول الشمس.", correct_answer:1, category:"science", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"الأرض والكواكب الأخرى تدور حول الشمس في مسارات إهليلجية." },
  { type:"true_false", question:"يقع نهر النيل في قارة آسيا.", correct_answer:2, category:"geography", age_min:5, age_max:99, difficulty:"easy", points:10, explanation:"نهر النيل يقع في قارة أفريقيا وليس آسيا." },
  { type:"true_false", question:"يتكون القرآن الكريم من 114 سورة.", correct_answer:1, category:"religion", age_min:11, age_max:99, difficulty:"medium", points:15, explanation:"يتكون القرآن الكريم من 114 سورة بالفعل." },

  // -- مطابقة (Matching): تُخزَّن الأزواج الصحيحة في pairs، وتُخلط جهة اليمين تلقائيًا عند العرض --
  { type:"matching", question:"طابق كل دولة بعاصمتها.", pairs:[
      { left:"عُمان", right:"مسقط" },
      { left:"اليابان", right:"طوكيو" },
      { left:"فرنسا", right:"باريس" },
      { left:"مصر", right:"القاهرة" },
    ], category:"geography", age_min:8, age_max:99, difficulty:"easy", points:15, explanation:"مسقط عاصمة عُمان، وطوكيو عاصمة اليابان، وباريس عاصمة فرنسا، والقاهرة عاصمة مصر." },
  { type:"matching", question:"طابق كل عالِم باكتشافه الأشهر.", pairs:[
      { left:"إسحاق نيوتن", right:"قوانين الحركة" },
      { left:"ألكسندر فليمنج", right:"البنسلين" },
      { left:"غريغور مندل", right:"علم الوراثة" },
      { left:"ديمتري مندليف", right:"الجدول الدوري" },
    ], category:"science", age_min:11, age_max:99, difficulty:"medium", points:20, explanation:"كل عالِم من هؤلاء اشتهر بالاكتشاف أو النظرية المذكورة أمامه." },

  // -- ترتيب (Ordering): تُخزَّن القائمة بالترتيب الصحيح في ordered_items، وتُخلط تلقائيًا عند بدء الاختبار --
  { type:"ordering", question:"رتّب الكواكب التالية من الأقرب إلى الأبعد عن الشمس.", ordered_items:["عطارد","الزهرة","الأرض","المريخ"], category:"science", age_min:8, age_max:99, difficulty:"medium", points:15, explanation:"الترتيب الصحيح بدءًا من الأقرب للشمس: عطارد، الزهرة، الأرض، ثم المريخ." },
  { type:"ordering", question:"رتّب هذه الأحداث التاريخية الإسلامية زمنيًا من الأقدم إلى الأحدث.", ordered_items:["بعثة النبي ﷺ","الهجرة النبوية","فتح مكة","وفاة النبي ﷺ"], category:"religion", age_min:11, age_max:99, difficulty:"medium", points:20, explanation:"بدأت البعثة، ثم الهجرة إلى المدينة، ثم فتح مكة، ثم وفاة النبي ﷺ." }

];

/* دالة مساعدة لتحويل مجموعة الأعمار النصية (مثل "11-13") إلى نطاق رقمي */
function ageGroupToRange(group){
  if (group === "18+") return { min: 18, max: 99 };
  const [min, max] = group.split("-").map(Number);
  return { min, max };
}
